### ISSUE TITLE
Add filtering to only include top X keyed histograms 

### ISSUE THREAD

**Issue by emtwo** [mozilla/bigquery-etl#1060]

**Comment by emtwo** [comment]
For some context, a keyed histogram is actually a set of related histograms each identified by a different key. Here is an example of one: https://glam.telemetry.mozilla.org/firefox/probe/application_reputation_server_verdict_2/explore?activeBuckets=%5B%22Safe%22%2C%22Uncommon%22%2C%22Dangerous%22%2C%22PotentiallyUnwanted%22%2C%22DangerousHost%22%2C%22Unknown%22%5D&process=parent&timeHorizon=ALL

Sometimes we have too many keys for a keyed histogram and we only need to show the top X number of keys that have the most data associated with them

**Comment by edugfilho** [comment]
We're tracking this in the GLAM repo now https://github.com/mozilla/glam/issues/2654
