### ISSUE TITLE
DAG generation: infer copy_dedupe dependencies

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#1089]
Currently, we must add explicit `depends_on` entries in `metadata.yaml` in order to generate `wait` sensors for stable tables in generated DAGs.

We already can determine via dry run that a given query depends on stable tables, and I think we should automatically inject sensors to wait on copy_deduplicate tasks based on stable table dependencies.

**Comment by scholtzan** [comment]
Sounds like a good idea. As a first step before implementing this, I think all the copy_deduplicate tasks should be moved to a common `copy_deduplicate` DAG. Currenly, `copy_deduplicate_main_ping`, for example, is part of the `main_summary` DAG while other tasks are in the `copy_deduplicate` DAG.

**Comment by jklukas** [comment]
I agree that there should be a single DAG for copy_dedupe and that `copy_deduplicate_main_ping` should be moved there.
