### ISSUE TITLE
publish_public_data tests failing on master

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#1107]
```
E           AssertionError: assert 4 == 3
 
E            +  where 4 = len([{'a': 'val1', 'b': '2', 'd': '2020-03-15'}, {'a': 'val3', 'b': '9', 'd': '2020-03-15'}, {'a': 'val2', 'b': '34', 'd': '2020-03-15'}, {'a': 'val1', 'b': '2', 'd': '2020-03-15'}])
 

 
tests/public_data/test_publish_public_data_json_script.py:63: AssertionError
 ```

See https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/4646/workflows/020d2799-0f26-41f5-a51e-8b09a8d5d488/jobs/17241/steps

cc @scholtzan

**Comment by scholtzan** [comment]
I re-ran the tests and they succeeded. I think this might have been another case of https://github.com/mozilla/bigquery-etl/issues/1051
