### ISSUE TITLE
Add gpu process histograms to glam

### ISSUE THREAD

**Issue by BenWu** [mozilla/bigquery-etl#1125]
Some histograms from gpu processes are keyed but probe info service doesn't tell us this so we may need to change the way the query is structured.

**Comment by BenWu** [comment]
There's a keyed boolean value in the probeinfo service response so that can be used.  We just need to handle the gpu process in https://github.com/mozilla/bigquery-etl/blob/master/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_v1.sql.py

**Comment by jrmuizel** [comment]
It would be nice to get this working to help diagnose https://bugzilla.mozilla.org/show_bug.cgi?id=1693636

**Comment by emtwo** [comment]
This should now be there. Please re-open if something is missing.
