### ISSUE TITLE
Run ETL for all Fenix products in Glam

### ISSUE THREAD

**Issue by emtwo** [mozilla/bigquery-etl#1130]
Right now only the release ETL is run.

**Comment by Ben-Wu** [comment]
ETL now running for `org_mozilla_firefox`, `org_mozilla_firefox_beta`, `org_mozilla_fenix`, and `org_mozilla_fennec_aurora`

PRs:
https://github.com/mozilla/bigquery-etl/pull/1183
https://github.com/mozilla/telemetry-airflow/pull/1098
