### ISSUE TITLE
Automatically remove outdated generated DAGs

### ISSUE THREAD

**Issue by scholtzan** [mozilla/bigquery-etl#1157]
Generated DAG files should get automatically deleted when their metadata entry gets removed. Currently, those DAG files will still exist in `dags/` and need to get removed manually.

**Comment by ANich** [comment]
This seems to now be the case with bigquery-etl DAGs being completely generated by CI correct? The files will be deleted and [IIUC](https://github.com/apache/airflow/discussions/21864#discussioncomment-2303337) the DAG will enter a  "deactivated" state cc @scholtzan @mikaeld
