### ISSUE TITLE
Include FxA device command events with type "notifyError"

### ISSUE THREAD

**Issue by rfk** [mozilla/bigquery-etl#1176]
In #1150 we export FxA device-command events to bigquery, but only if they have `type` field equal to one of 'device.command.invoked', 'device.command.notified', or 'device.command.retrieved'. Could we please also add `device.command.notifyError` to this list?

(Greedily, I'd prefer to match on `LIKE device.command.%` in order to pick up any future events automatically, but I can see how a fixed list may be preferable from a pipeline standpoint, and I don't have any plans to add additional event types to this list any time soon).

**Comment by jklukas** [comment]
> (Greedily, I'd prefer to match on LIKE device.command.% in order to pick up any future events automatically, but I can see how a fixed list may be preferable from a pipeline standpoint, and I don't have any plans to add additional event types to this list any time soon).

I'm fine with this. It seems unlikely that we'd get new events that we don't want, and we can modify to go back to an explicit list if that does change in the future.
