### ISSUE TITLE
Edit on Github link in docs doesn't work

### ISSUE THREAD

**Issue by tdsmith** [mozilla/bigquery-etl#1242]
From https://mozilla.github.io/bigquery-etl/mozfun/norm/, the "Edit on Github" link in the top right 404s.

**Comment by jklukas** [comment]
Verified. cc @scholtzan

**Comment by wlach** [comment]
So two things:

* We should probably just leave these URLs out of the configuration, as there's not really a one-to-one mapping between URLs and files with this documentation: https://www.mkdocs.org/user-guide/configuration/#edit_uri
* We *can* however include a link to their definition in the autogenerated documentation, probably immediately below the explanatory text. e.g. the product_info function code/definitions live in: https://github.com/mozilla/bigquery-etl/blob/master/sql/mozfun/norm/product_info

After setting up the environment (see the README), you should be able to generate a local copy of the docs with this URL: https://github.com/mozilla/bigquery-etl/blob/master/script/generate_docs

**Comment by wlach** [comment]
@hngerebara would you like to give this a try? (@scholtzan @jklukas feel free to chime in you have other / better ideas on how to do this)

**Comment by jklukas** [comment]
> We can however include a link to their definition in the autogenerated documentation

Indeed. I think probably the best thing would be to mimic the "Edit in GitHub" style link. So the docs for `norm.product_info` would have the following link: https://github.com/mozilla/bigquery-etl/edit/master/sql/mozfun/norm/product_info/metadata.yaml which takes you right to the editor interface for the associated `metadata.yaml`. This isn't perfect, since the docs for each function are compiled from both the `metadata.yaml` and the `README.md` in the function's folder, and also might reference SQL examples. But there are only a few cases where we have significant content outside of `metadata.yaml`, so I think linking to that file gets us 90% of the way there.

**Comment by wlach** [comment]
> > We can however include a link to their definition in the autogenerated documentation
> 
> Indeed. I think probably the best thing would be to mimic the "Edit in GitHub" style link. So the docs for `norm.product_info` would have the following link: https://github.com/mozilla/bigquery-etl/edit/master/sql/mozfun/norm/product_info/metadata.yaml which takes you right to the editor interface for the associated `metadata.yaml`. This isn't perfect, since the docs for each function are compiled from both the `metadata.yaml` and the `README.md` in the function's folder, and also might reference SQL examples. But there are only a few cases where we have significant content outside of `metadata.yaml`, so I think linking to that file gets us 90% of the way there.

It might be nice to be able to easily look up the SQL, etc. for reference (which is why I proposed linking to the directory where the definition lives)-- but perhaps that can be done in a followup issue.

**Comment by jklukas** [comment]
> It might be nice to be able to easily look up the SQL, etc. for reference (which is why I proposed linking to the directory where the definition lives)-- but perhaps that can be done in a followup issue.

Great point. Perhaps each function's docs can end with two links: Source and Edit. Source would take them to the directory for the function, and Edit would take them to the edit interface for metadata.yaml.

**Comment by hngerebara** [comment]
Okay will do

**Comment by wlach** [comment]
@Iinh is going to look at this one

**Comment by jklukas** [comment]
I just took a look at the published output after this change, and it's lovely. Nice work, @Iinh!
