### ISSUE TITLE
publish_views failure: dataset not found

### ISSUE THREAD

**Issue by whd** [mozilla/bigquery-etl#1318]
/CC @fbertsch @scholtzan 

Looks like this is missing some qualification. I don't see this as excluded from CI so perhaps this could have been detected somewhere.

```
google.api_core.exceptions.NotFound: 404 Not found: Dataset OPS_ADMIN_PROJECT:org_mozilla_firefox_derived was not found in location US

         -----Query Job SQL Follows-----          

    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE VIEW
   2:  moz-fx-data-shared-prod.events_daily
   3:AS
   4:SELECT
   5:  *
   6:FROM
   7:  org_mozilla_firefox_derived.events_daily_v1
```

**Comment by scholtzan** [comment]
https://github.com/mozilla/bigquery-etl/pull/1319 fixes this.

Looks like the dry run succeeded for the view. I guess we should add some extra checks to make sure project IDs aren't missing for referenced tables in view definitions.
