### ISSUE TITLE
CI checks for fully-qualified names in view definitions

### ISSUE THREAD

**Issue by scholtzan** [mozilla/bigquery-etl#1320]
Follow-up to https://github.com/mozilla/bigquery-etl/pull/1319
We should add some checks to the CI to make sure view definitions use fully-qualified names of referenced tables.

**Comment by ANich** [comment]
I think this was closed by https://github.com/mozilla/bigquery-etl/pull/3411? cc @scholtzan

**Comment by kik-kik** [comment]
Is this issue addressing the same issue as described here?
https://github.com/mozilla/bigquery-etl/issues/1413

@scholtzan

**Comment by scholtzan** [comment]
yup that's the issue
