### ISSUE TITLE
bqetl udf create with non-udf dataset results in untestable udf

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#1342]
The default configuration for `bq udf create`, when used with a dataset that is not `udf`, is to create a new subdirectory within `/udf` with that dataset name. Unfortunately this causes any udfs in that directory to fail [here](https://github.com/mozilla/bigquery-etl/blob/master/bigquery_etl/udf/parse_udf.py#L135), because the udf name's dataset is presumed to be `udf`.

We need to treat these [like `mozfun` udfs](https://github.com/mozilla/bigquery-etl/blob/master/bigquery_etl/udf/parse_udf.py#L125).

**Comment by scholtzan** [comment]
Fixed via https://github.com/mozilla/bigquery-etl/pull/1399
