### ISSUE TITLE
Support stored procedures alongside UDFs

### ISSUE THREAD

**Issue by scholtzan** [mozilla/bigquery-etl#1347]
We should add support for stored procedures, storing them alongside UDFs in `procedure.sql` files and expanding the testing, publishing mechanisms.

**Comment by fbertsch** [comment]
With https://github.com/mozilla/bigquery-etl/pull/1358 to be merged, this is mostly done. However I'm not happy with the current codebase retaining `UDF`, e.g. `RawUDF` and `ParsedUDF` classes, but now includes procedures.

The BQ API [refers to them generically](https://cloud.google.com/bigquery/docs/reference/rest#rest-resource:-v2.routines) as `routines`, which we could do here in the codebase.

**Comment by fbertsch** [comment]
Fixed with #1358, #1355, and #1343.
