### ISSUE TITLE
Support stored procedures explicitly

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#1378]
Currently, `bqetl udf ...` is udf-focused. We now support (to a varying degree) stored procedures, and need to support them explicitly.

Here are a few of the problems I've noticed so far:

- A `bqetl udf create` alternative that creates stored procedures
- A `bqetl udf rename` alternative that renames stored procedures

It's not clear to me whether we want this to be a flag (e.g. `bqetl udf create --procedure`) or a separate command (`bqetl procedure create`). We could move them to one: `bqetl routine create --udf/--procedure`.

**Comment by scholtzan** [comment]
Supported via https://github.com/mozilla/bigquery-etl/pull/1442

Creating new UDFs would look like: `bqetl routine create udf.test_udf --udf` or `bqetl mozfun create json.test_udf --udf`

Creating new stored procedures would look like: `bqetl routine create udf.test_udf --stored_procedure` or `bqetl mozfun create json.test_udf --stored_procedure`

The default project is shared prod, but the `--project_id` options allows to change that
