### ISSUE TITLE
Generated docs missing `event_analysis`

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#1385]
The doc link recently went out in data gazette: https://mozilla.github.io/bigquery-etl/mozfun/event_analysis/

However, the recent change in the structure seems to have removed that dataset from the docs. cc @scholtzan

**Comment by fbertsch** [comment]
In the meantime, the docs are here: https://github.com/mozilla/bigquery-etl/blob/bcb95bb449431aff13322a7bcf9e0a5c0cd240d7/mozfun/event_analysis/create_events_view/README.md

**Comment by scholtzan** [comment]
The current URL to the docs for this dataset is: https://mozilla.github.io/bigquery-etl/sql/mozfun/event_analysis/
It's probably best to drop the `sql/` part. I'll work on a fix for this.
