### ISSUE TITLE
Deploy UDFs in CI

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#1406]
We currently have a bit of a confusing state, where UDF documentation deploys during CI, but UDFs don't deploy until the next day. This can result in available documentation for a UDF, but no deployed version available.

Instead, we should deploy the UDF first, and once that succeeds, deploy the documentation.

**Comment by jklukas** [comment]
A wrinkle here is that the structure of `mozfun` means we need to be able to provision new datasets on demand. We have a special task in Airflow for deploying `mozfun` partly for that permissions situation. We'd need to have a discussion with data ops if we wanted to change the permissions model.

**Comment by scholtzan** [comment]
Instead of doing this via CI directly we'll trigger the Airflow deploy task when PRs get merged
