### ISSUE TITLE
Explicit CI check to make sure project IDs aren't missing for referenced tables in view definitions

### ISSUE THREAD

**Issue by whd** [mozilla/bigquery-etl#1413]
https://github.com/mozilla/bigquery-etl/issues/1318
https://github.com/mozilla/bigquery-etl/issues/1409
https://github.com/mozilla/bigquery-etl/issues/1422
https://github.com/mozilla/bigquery-etl/pull/1705

**Comment by jklukas** [comment]
We may be able to solve this somewhat naturally as part of implementing a `mozdata` project. Once we "cut over" to mozdata for user queries, I think bigquery-etl should put all user-facing views underneath `sql/mozdata`, and then we could have CI attempt to publish the views in a test project rather than using the shared-prod dryrun service.

**Comment by whd** [comment]
Given related issues like https://github.com/mozilla/bigquery-etl/issues/1422#issuecomment-706827788 it does seem like the easiest thing to do here would be to attempt to publish views on CI. Dry run is clearly insufficient as we seem to be having an increasing number of these failures lately.

**Comment by relud** [comment]
this CI check can be accomplished by modifying the dry-run script to not provide a default project or dataset when dry-running view definitions

**Comment by relud** [comment]
> this CI check can be accomplished by modifying the dry-run script to not provide a default project or dataset when dry-running view definitions

I was wrong, the bigquery API doesn't have a default project parameter. When project is missing it defaults to the project where the query was submitted.

This means a dry run can only detect if `datasetId` was not specified or does not exist.

A workaround here would be to dry run views in a project with no BQ datasets, and translate the error from `Not
  found: Dataset some-project:some_dataset` to something like `Dataset name "some_dataset" missing project in view definition`.

**Comment by scholtzan** [comment]
https://github.com/mozilla/bigquery-etl/pull/1711 adds a step to the CI for validating view definitions. It checks that view names have project IDs and makes sure directory the structure matches the view content.

**Comment by fbertsch** [comment]
Still an issue. This was uncaught: https://github.com/mozilla/bigquery-etl/pull/1797/files

**Comment by jklukas** [comment]
It looks like [`default_dataset` in a query can include project_id](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.job.QueryJobConfig.html#google.cloud.bigquery.job.QueryJobConfig.default_dataset). I was under the impression that a query job would always have the default project be set to the project that the query is running in, but that may not be true if default_dataset includes a project qualifier. If that holds, we may not need to maintain multiple dry run services. It would also mean that we could dry run views with the project set to some random dataset, which would better guarantee that all references are fully qualified.

**Comment by jklukas** [comment]
> It looks like default_dataset in a query can include project_id

Indeed this seems to work. Here's a demonstration:

```
# Create a table in mozdata.analysis for testing
bq query --nouse_legacy_sql --project_id=mozdata "CREATE OR REPLACE TABLE mozdata.analysis.klukas_prjtest1 AS SELECT 3 AS three"

# Issue a query in a different project that successfully uses an unqualified table reference
bq query --nouse_legacy_sql --project_id=mozdata-nonprod --dataset_id=mozdata:analysis "SELECT * FROM klukas_prjtest1"
```

**Comment by fbertsch** [comment]
However, it doesn't default to the project specified in `dataset_id` when a different dataset is specified:
```
bq query --nouse_legacy_sql --project_id=mozdata-nonprod --dataset_id=mozdata:org_mozilla_firefox "SELECT * FROM analysis.klukas_prjtest1"
BigQuery error in query operation: Error processing job 'mozdata-nonprod:bqjob_rb678487a7c97425_0000017791c1793b_1': Not found: Table mozdata-nonprod:analysis.klukas_prjtest1 was not found in location US
```

**Comment by jklukas** [comment]
Reading the docs more thoroughly, I see it even points out this limitation:

> Note that this does not alter behavior of unqualified dataset names.

**Comment by jklukas** [comment]
An alternative here could be to deploy a dry run service in an additional project where no tables or views live. If a view definition uses only fully-qualified references, then we would expect it to be able to succeed regardless of the project_id of the request.

**Comment by relud** [comment]
> An alternative here could be to deploy a dry run service in an additional project where no tables or views live. If a view definition uses only fully-qualified references, then we would expect it to be able to succeed regardless of the project_id of the request.

this is what we should do

**Comment by whd** [comment]
Also https://github.com/mozilla/bigquery-etl/issues/2124, looks like this one might have only been an issue because tests were disabled

**Comment by kik-kik** [comment]
@scholtzan isn't this already happening?

**Comment by scholtzan** [comment]
indeed we are: https://github.com/mozilla/bigquery-etl/blob/8423c7ad2e6323a29302d09291a72d3624b1b600/bigquery_etl/view/__init__.py#LL176C38-L176C38
