### ISSUE TITLE
publish_views: google.api_core.exceptions.BadRequest: 400 Syntax error: Unclosed identifier literal

### ISSUE THREAD

**Issue by whd** [mozilla/bigquery-etl#1422]
/CC @scholtzan 

Guessing this has something to do with replacement logic, because the view [looks fine](https://github.com/mozilla/bigquery-etl/blob/master/sql/moz-fx-data-shared-prod/mozilla_vpn/waitlist/view.sql#L2). I vaguely recall this happening before but for an unrelated reason (#1232).

```
   1:CREATE OR REPLACE VIEW
   2:  `moz-fx-data-shared-prod.mozilla_vpn.waitlist
   3:AS
   4:SELECT
   5:  *
   6:FROM
   7:  `moz-fx-data-shared-prod`.mozilla_vpn_derived.waitlist_v1
```

**Comment by scholtzan** [comment]
The backticks need to enclose the entire view name, not just the project part. I pushed a fix in https://github.com/mozilla/bigquery-etl/pull/1423

**Comment by relud** [comment]
@whd can you check that this fixed it?
