### ISSUE TITLE
clients_scalar_probe_counts_v1 exceeds resources for shuffle

### ISSUE THREAD

**Issue by BenWu** [mozilla/bigquery-etl#1432]
```
Resources exceeded during
query execution: Your project or organization exceeded the maximum disk and
memory limit available for shuffle operations. Consider provisioning more slots,
reducing query concurrency, or using more efficient logic in this job.
```

The `clients_scalar_probe_counts_v1` query intermittently fails due to resources exceeded.  It seems to work on the retry, possibly because there are fewer running queries at that time.  There may be some query optimizations we could make to avoid this.

**Comment by Ben-Wu** [comment]
Changed task dependencies so client_scalar_probe_counts runs after scalar_percentiles https://github.com/mozilla/telemetry-airflow/pull/1169

This may have fixed the issue for now but a more reliable solution would be ideal

**Comment by BenWu** [comment]
fixed by ^
