### ISSUE TITLE
Filter on fxa_content_auth_events_v1 causes some events to be dropped

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/bigquery-etl#144]
Here's an example [of an event that makes it to amplitude](https://analytics.amplitude.com/mozilla-corp/project/178231/search/amplitude_id%3D94856552497) but is filtered out by the current content server ETL job. 

([querying for its flow_id in fxa_content_events_v1](
https://console.cloud.google.com/bigquery?sq=630180991450:91df42e689824ef090fd48643b78aa0d
) shows its missing, but its [there in the FxA logs](
https://console.cloud.google.com/bigquery?sq=630180991450:d092f47a85a34c9e9eed7afb6a4afcda
))

I think this is because of this line in the etl job:
https://github.com/mozilla/bigquery-etl/blob/master/sql/fxa_content_events_v1.sql#L14

This causes many form views of relier-hosted forms to be filtered out, for example form views on about:welcome that are logged via a call to the FxA metrics endpoint. Without these view events its not possible to construct an end-to-end funnel that begins on the relier's site. 

Based on querying for null user ids in the FxA logs, I think removing this filter would add another 3M events per day to the derived datasets.

These are almost all this `fxa_email_first - view` event. Compare [GCP](https://datastudio.google.com/u/0/reporting/1jtdSRQHSBWwko-Vg4udZv2Zo3JR4UM22/page/kb4p/edit) with [amplitude](https://analytics.amplitude.com/mozilla-corp/chart/rszb8rv).

I do think we need these events for some analyses, but I'm guessing it would be costly to backfill them, so maybe we can start by just removing the filter going forward? Or would that break something else that I'm not aware of. I think we would at least have to make `user_id` nullable (if its not already). 

The filter can stay on the auth server ETL, there will never be null user_ids there.

**Comment by jklukas** [comment]
This sounds reasonable. Events without user_id won't contribute to MAU, so this change should have no effect on the existing uses of the tables for KPI dashboarding.

Removing the filter going forward sounds good.

**Comment by irrationalagent** [comment]
> This sounds reasonable. Events without user_id won't contribute to MAU, so this change should have no effect on the existing uses of the tables for KPI dashboarding.

yep, confirming this. 

do you know if there's anything else that would need to be done besides just removing that filter? if not, I can put up the pr.

**Comment by jklukas** [comment]
`user_id` is already nullable and we already have a filter in `fxa_users_daily` to ignore rows with null user_id, so I think we're good. Do feel free to put up a PR.
