### ISSUE TITLE
Modify GLAM ETL for Fenix to write out to glam-fenix-dev project

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/bigquery-etl#1457]
The ETL currently assumes it lives in a `glam_etl` dataset in `moz-fx-data-shared-prod`, but this is unlikely to be the final production location.

**Comment by whd** [comment]
I've filed https://github.com/mozilla-services/cloudops-infra/pull/2629 which is expected to replace `glam-fenix-dev` for the production environment.
