### ISSUE TITLE
Add test for up to date udfs in queries

### ISSUE THREAD

**Issue by relud** [mozilla/bigquery-etl#148]
for each function in `udf/` we should test that if used in a query in `sql/` the function should be present at the top of the query and actually match the code provided in `udf/`

**Comment by jklukas** [comment]
I am starting into implementation for a first phase of #141. I am hoping that phase two can involve injecting udfs to the top of queries, in which case we can remove them from the source files and not have to worry about testing this.

**Comment by jklukas** [comment]
This is no longer needed now that we have templates.
