### ISSUE TITLE
Remove filter for desktop browser search metrics in GLAM

### ISSUE THREAD

**Issue by robhudson** [mozilla/bigquery-etl#1483]
A user of GLAM searched for `browser_searchinit_engine_invalid_webextension` and it was not there. The metric was found in the probe search API so it appeared that GLAM would load it but the GLAM data response was empty.

The reason is that GLAM filters out metrics related to search to avoid exposing those numbers to any employee:
https://github.com/mozilla/bigquery-etl/blob/master/sql/moz-fx-data-shared-prod/telemetry/client_probe_counts_v1/view.sql#L29-L32

Frank shared that the search datasets are available to all employees now and this is no longer required. If GLAM ever does expose data to the general public we can filter out search metrics via the front-end.

**Comment by Ben-Wu** [comment]
Bug to remove restrictions on search https://bugzilla.mozilla.org/show_bug.cgi?id=1623180
