### ISSUE TITLE
Produce clients_daily directly from main_v4 rather than main_summary

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#1516]
We have deprecated `main_summary` and generally are not adding new fields there, but `clients_daily` still depends on it. One major reason I'm aware of is that `main_summary` contains more history than `main_v4`, allows `clients_daily` to stretch back to 2016.

But are there other reasons? It would be nice to simplify the ETL structure and remove `main_summary` as a failure mode for downstream desktop ETL. Could we consider "archiving" the current clients_daily query for large-scale backfill scenarios, and otherwise replace the query with one on top of `main_v4` directly?

cc @relud Who I expect has the most context here.

**Comment by relud** [comment]
This was previously attempted in #482, and is mostly an exercise in copying main_summary_v4 logic into clients_daily_v6, which seemed like unnecessary duplication, but the benefit is clear to me now.

There was also a short-term backfill concern that some necessary fields in main_v4 were in additional_properties until November 2019, and referencing additional_properties significantly increases the cost of the query. Now that those have been out of additional_properties for a year, I think it would be fine to stop referencing additional_properties when building those fields.

I'll take a stab at this.

**Comment by relud** [comment]
it's not currently possible to produce clients_daily from main_v4 in a single step, because it produces a too-complex query.

As an alternative solution, I am attempting to produce a subset of main_summary columns needed specifically for clients_daily without resorting to run_multipart_query.

**Comment by relud** [comment]
> it's not currently possible to produce clients_daily from main_v4 in a single step, because it produces a too-complex query.
> 
> As an alternative solution, I am attempting to produce a subset of main_summary columns needed specifically for clients_daily without resorting to run_multipart_query.

klukas was able to get complexity down, and i'm currently working on fixing up tests and validating that it doesn't change any behavior.
