### ISSUE TITLE
Include descriptions with each generated DAG

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#1534]
@haroldwoo is upgrading our Airflow cluster to 1.10.12 and noted that DAGs can now have markdown rendered in the Airflow UI by setting the `dag.docs_md` attribute. We should consider adding a `description` field to `dags.yaml` that will get injected as `docs_md` in the DAG.

**Comment by jklukas** [comment]
Example usage: https://geoffruddock.com/markdown-documentation-in-airflow-dags/

**Comment by haroldwoo** [comment]
an example from our repo: https://github.com/mozilla/telemetry-airflow/blob/master/dags/clean_gke_pods.py#L7-L34
