### ISSUE TITLE
Support verification queries

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#1544]
A common pattern (and one that we don't use) is to run an ETL, check that the data is correct, and then make it available to prod.

We should support that in this repo. A straightforward way would be to:
1. Run the query, and load data into a tmp table
2. Run an optional `check.sql` that returns a single row with a single boolean
  If `False`: Airflow Error
  If `True`: Move the data to prod, and delete the tmp table

**Comment by fbertsch** [comment]
It might be worth it to keep the tmp table available after error, and include the name of it in the logs so the engineer can inspect it.

**Comment by jklukas** [comment]
I've never deeply looked into data testing tools, but the idea here sounds similar to some of the concepts in https://docs.getdbt.com/docs/building-a-dbt-project/tests ; we should definitely do a short survey of data testing tools before jumping into this. Even if none of the tools are directly usable in our case, we can perhaps integrate some best practices about how to approach the problem.

Are there specific cases you have in mind where we've had a regression that could have been caught by a test like this?

**Comment by fbertsch** [comment]
> I've never deeply looked into data testing tools, but the idea here sounds similar to some of the concepts in https://docs.getdbt.com/docs/building-a-dbt-project/tests ; we should definitely do a short survey of data testing tools before jumping into this. Even if none of the tools are directly usable in our case, we can perhaps integrate some best practices about how to approach the problem.

Agreed. In the past I've used tools that rolled back changes from e.g. Postgres, but that's not really applicable here.

> Are there specific cases you have in mind where we've had a regression that could have been caught by a test like this?

I'm not 100% sure, but we could have perhaps caught [this issue](https://github.com/mozilla/bigquery-etl/issues/1545) (hard to say though, since it was a git problem). We've also caught issues in telemetry-dashboard with a similar approach (except using re:dash alerts).

**Comment by ANich** [comment]
This is more or less implemented now - https://mozilla.github.io/bigquery-etl/reference/data_checks/. cc @fbertsch if there's something from this issue that's worth splitting into another one

**Comment by fbertsch** [comment]
Only one I could see is using tmp tables in prod. I'll put this in as a discussion for next week's data platform infra wg.
