### ISSUE TITLE
Generate summaries of derived tables generated in this repo

### ISSUE THREAD

**Issue by wlach** [mozilla/bigquery-etl#1589]
In #1102, @scholtzan added auto-generated documentation for the UDFs, which are now published at https://mozilla.github.io/bigquery-etl/ 

For example:

https://mozilla.github.io/bigquery-etl/mozfun/bits28/

It would be handy to *also* generate some basic documentation for the views and derived tables that we have in this repository, as a useful intermediate step before we make this information available in the Glean dictionary ([see "phase 2" of the proposal](https://docs.google.com/document/d/1OkTWA3rsSJ0m5g9GDnxXVUMkJP-xJMQk_bDgDq-Z9xM/edit#heading=h.aw6yt7u3a2r2)). I expect that the audience for this would mostly be data engineering, although people from data science may also occasionally find this useful.

It's not completely clear to me, off the cuff, what the best initial organization would be of this information. Views are currently quite bare-bone (with no metadata at all), since they're intended mainly as a convenience mechanism for accessing the underlying table:

https://github.com/mozilla/bigquery-etl/tree/master/sql/moz-fx-data-shared-prod/telemetry/main_summary_v4

Derived tables have a few more fields, but are also fairly bare bone:

https://github.com/mozilla/bigquery-etl/tree/master/sql/moz-fx-data-shared-prod/telemetry_derived/main_summary_v4

However, we could probably augment this information in many cases with metadata that is in docs.tmo, for example:

https://docs.telemetry.mozilla.org/datasets/batch_view/main_summary/reference.html

(this might be better as a follow-on to an initial implementation)

--

For an initial attempt, just surfacing the basic metadata (description, name, owner, scheduling information) of the derived datasets (ignoring views) along with a link to the file in the repository seems like a sensible place to start. After that's done, perhaps we can figure out a strategy for displaying views at the same time. To provide some kind of loose organization for the documentation, I would propose breaking it down by GCP project, which would include:

* glam-fenix-dev/glam_etl 
* moz-fx-data-marketing-prod 
* moz-fx-data-shared-prod 

You can see the structure by looking at the contents of the `sql` directory (https://github.com/mozilla/bigquery-etl/tree/master/sql) -- note that there are some directories in there which do not refer to derived datasets.

**Comment by jklukas** [comment]
In many cases, we have added reasonable descriptions to the `metadata.yaml` for the underlying table, and that description could equally apply to the user-facing view on top of it. We should likely copy those descriptions to the directories for the views.

To help avoid bloat, I think we should publish docs _only_ for user-facing views, so ignore anything in `*_derived` directories. This also matches what users experience in redash, which sees only the republished views.

I expect we would ignore `glam-fenix-dev` as that project is an implementation detail. If we want to make that data available to users, we should provision views under shared-prod that would then be available to redash, etc.

Marketing data, _is_ exposed to redash via a separate data source. It would make sense to publish docs for user-facing views in that project.

I would love to see the published docs specify which redash data source each project corresponds to.
