### ISSUE TITLE
Remove UDF declarations from queries

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#159]
Follow-up to #141 

- Extend the code in `tests/parse_udfs.py` to also read through the files under sql/ and identify usage of udfs there
- Write a python script to use the above udf dependency resolution logic, writing out generated sql files to a new directory (perhaps we call this `target/sql` to match Maven's conventions); each file would contain the body of all temporary UDFs needed in the query, and then the query text itself
- Remove UDF declarations from the source files under `sql/` and update the logic for our CircleCI `deploy` job to make sure that the published container has a `sql/` directory that contains the generated queries with UDF definitions

**Comment by jklukas** [comment]
This would supersede #148

**Comment by scholtzan** [comment]
I'll work on this.
