### ISSUE TITLE
Support custom query parameters in dry run

### ISSUE THREAD

**Issue by BenWu** [mozilla/bigquery-etl#1595]
Dry run currently only sets the submission_date query param so there are a lot of queries that are skipped in dry run because they use additional params (particularly for glam).  It would be useful to be able to dry run these as an additional sanity check.

The dry run cloud function can take an optional list of params and there can be an additional list in dryrun.py for parameterized queries so the queries will just be a different special case.

**Comment by ANich** [comment]
This was fixed in https://github.com/mozilla/bigquery-etl/pull/2122
