### ISSUE TITLE
Feedback on main_1pct

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#1597]
We implemented a "preview" table called `telemetry.main_1pct` in https://github.com/mozilla/bigquery-etl/pull/1571 (docs included there) in order to make it available to users and gather feedback. The plan is to keep this around for ~1 month to see if users find it useful and whether any changes are needed before making a decision to fully commit to it.

Folks interested in this view should watch this issue and please leave feedback. If you agree with feedback someone has already left, please utilize the 👍  reaction to provide signal that you agree.

**Comment by irrationalagent** [comment]
I have not used this yet, but I have some projects on my plate that would make use of it in the future. I've been adding subsample_id to some of my own personal-use tables so I think that's a nice feature.

**Comment by acmiyaguchi** [comment]
This works well -- queries complete quicker via STMO than querying the main ping table with the sample id filter.

**Comment by jklukas** [comment]
## Final week for feedback

I've seen this table in use enough that I'm convinced it's worth supporting long-term and bringing out of beta. I will give it one more week for feedback on any particulars. Absent any feedback to motivate a change, we'll consider the structure frozen on 2021-01-22, and I'll send out communication that the table has graduated to general availability.

Outstanding questions that I would still like feedback on:

- Is a 6 month retention period reasonable? Are there use cases that would call for a longer history?
- Is `subsample_id` useful? Is the current definition fine or are there suggestions for a better definition?
- Are there additional sampled tables that would be high value? Perhaps `main_nightly`?

**Comment by jklukas** [comment]
We've just created `main_nightly` which is currently being backfilled: https://github.com/mozilla/bigquery-etl/pull/1690

**Comment by jklukas** [comment]
I missed closing this out on 2021-01-22, but I now consider `main_1pct` and `main_nightly` out of beta. I need to update docs and send out communication.

**Comment by jklukas** [comment]
Removing warnings from the table metadata: https://github.com/mozilla/bigquery-etl/pull/1722

**Comment by jklukas** [comment]
Announced: https://mail.mozilla.org/pipermail/fx-data-dev/2021-January/000392.html
