### ISSUE TITLE
Function names in the docs left sidebar are flowing out of div

### ISSUE THREAD

**Issue by Iinh** [mozilla/bigquery-etl#1609]
<img width="836" alt="text-overflow" src="https://user-images.githubusercontent.com/28797553/101788699-3d7c9b00-3ab5-11eb-8702-ef51e0c009b7.png">

See: https://mozilla.github.io/bigquery-etl/mozfun/event_analysis/ 

Potential fix could include [configuring mkdocs css and javascript](https://www.mkdocs.org/user-guide/configuration/#extra_css). However I’m leaning more towards using a different theme that has better UI, such as [material](https://github.com/squidfunk/mkdocs-material), to avoid tampering with the original css code.

**Comment by scholtzan** [comment]
The material theme for mkdocs looks neat! It would definitely be nice if we don't have to write custom CSS and keep maintaining it.
