### ISSUE TITLE
Update bqetl CLI to work with python 3.9

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/bigquery-etl#1611]
I'm in mac os python version hell and am now on 3.9 locally, but the mozilla-bigquery-etl specifies 3.8.*

**Comment by wlach** [comment]
I doubt there's any particular reason we need to require 3.8, and not `>=3.8`. We can fix this here:

https://github.com/mozilla/bigquery-etl/blob/0d6a88752a4b87f9ac6fc8d4bc76d7677673a08b/setup.py#L46

@scholtzan can you confirm?
