### ISSUE TITLE
Allow validation of airflow dag generation locally

### ISSUE THREAD

**Issue by wlach** [mozilla/bigquery-etl#1643]
Currently we run (and validate) airflow dag generation in CI, but not locally. This can create confusing situations where something appears to work fine locally, but fail in CI (see #1512). It would be good if we could catch at least common failures regarding airflow dag generation locally. Need to flesh out a bit what that would mean.

**Comment by scholtzan** [comment]
This sounds like it is related to https://github.com/mozilla/bigquery-etl/issues/1582. Another issues is that the Airflow DAG generation relies on the dry running service which is sometimes flaky. So it can happen that the DAG generation works fine locally but the a timeout occurs for dry running some query when generating the DAGs in the CI.
