### ISSUE TITLE
Add gunzip udf to mozfun

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/bigquery-etl#1653]
I've been using `moz-fx-data-shared-prod.udf_js.gunzip` for looking through payload_bytes_errors. I think this is used often enough to be put into mozfun.

https://github.com/mozilla/bigquery-etl/blob/master/sql/moz-fx-data-shared-prod/udf_js/gunzip/udf.sql

Naming is the most difficult. It might make sense to have a miscellaneous utils dataset e.g. `mozfun.utils.gunzip`.

**Comment by jklukas** [comment]
I don't want to add JS functions to mozfun without it being very apparent. So if we move forward with this, I would recommend a dataset name including  a `_js` suffix or having js in the function name.

> I think this is used often enough to be put into mozfun.

I would argue that this is only relevant to data sre and data eng and should not be user-facing, so maybe shouldn't be in mozfun at all. Or perhaps it means it should be under a datset for "admin" or "ops".
