### ISSUE TITLE
Productionize fields from ccd_feature_set

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#1678]
I've been chatting with @SuYoungHong @irrationalagent @godelstheory about productionizing an experimental table for feature usage:

- [draft query](https://console.cloud.google.com/bigquery?project=moz-fx-data-derived-datasets&folder=&organizationId=&sq=630180991450:407629d0964442b3a814efcaed9837ae)
- [spreadsheet documenting the fields](https://docs.google.com/spreadsheets/d/1zlGi4C6qqEEUkyh2VFAIbyGl6y2J_AnfaH6RYNXFbx8/edit#gid=0)

**Comment by jklukas** [comment]
## Extracting event counts from histograms

I understand the fields here that are looking at the '$.sum' from a histogram, but it's less clear to me what the intention is behind lines like:

```
SUM(COALESCE(ARRAY_LENGTH(`moz-fx-data-shared-prod.udf.json_extract_histogram`(payload.processes.content.histograms.video_play_time_ms).values), 0)) AS video_play_time_ms_count
```

This ARRAY_LENGTH calculation is perhaps trying to get the number of buckets that are populated? And we infer that the number of populated buckets corresponds to the number of distinct videos played? If so, I think that methodology is problematic as it assumes that every entry in the `values` array has a value of 1. But many histograms include empty buckets on the extremes, or may have multiple entries in a given bucket.

```
  (SELECT SUM(value) FROM UNNEST(mozfun.hist.extract(payload.processes.content.histograms.video_play_time_ms).values)) AS video_play_time_ms_count
```

See https://sql.telemetry.mozilla.org/queries/77400/source

Am I interpreting intent correctly?

**Comment by godelstheory** [comment]
Yes, your interpretation is correct, and the `ARRAY_LENGTH` query is incorrect consequently. Your query using `SUM(value)` gets at the desired result.

**Comment by irrationalagent** [comment]
FWIW I revised the query based on Jeff's feedback, and also fixed a couple of things in the events section. If I find anything else ill continue to update the link below. I can't guarantee that its complete in the sense of having every measure we might care about (it almost certainly doesn't)

https://sql.telemetry.mozilla.org/queries/77408/source

**Comment by jklukas** [comment]
I have a tentative plan put together in the [daily per-client aggregations Data Warehouse project doc](https://docs.google.com/document/d/1Lml-hWiqhvUazjn_-sDF6TUvwAEA3jMG3LJbyIC7fEc/edit#heading=h.plzmoduquen2) about how to maintain a `clients_last_seen_event` table and join that into the `clients_last_seen` view.

I expect to be able to proceed here via two separate PRs: one to add the main ping-based fields, and then a separate one to define the new event ping-based pathway.

**Comment by godelstheory** [comment]
Updated [query](
https://console.cloud.google.com/bigquery?sq=687003905036:1dbc6f07e9474460ae91d8cf946917d5
) and [spreadsheet](https://docs.google.com/spreadsheets/d/1zlGi4C6qqEEUkyh2VFAIbyGl6y2J_AnfaH6RYNXFbx8/edit#gid=1044522614) to reflect above conversation.

**Comment by jklukas** [comment]
## Naming patterns

I want to introduce consistency in naming as much as possible for these fields. In https://github.com/mozilla/bigquery-etl/pull/1696 I'm making the decision to name these event-based fields with the following pattern:

In clients_daily_event: counts are called `n_<verb>_<subject>`, so `n_logged_event`, `n_created_pictureinpicture`, `n_viewed_protection_report`.

In clients_last_seen_event: bit patterns are called `days_<verb>_<subject>_bits`, so `days_logged_event_bits`, `days_used_pictureinpicture`.

I'm also erring on the side of sticking to terminology from the events themselves. So `pictureinpicture` is the category string and we maintain that in the field name, rather than using `pip`. I feel like a bit more editorializing is appropriate at the clients_last_seen level, though; hence `n_created_pictureinpicture` (which maintains "create" from the event's terminology) gets aggregated to `days_used_pictureinpicture` (logically, we are using this to measure usage of the pictureinpicture feature).

Feedback on that strategy is welcome.
