### ISSUE TITLE
fxa_auth_events source schema incompatible change

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#1684]
We had to null out `jsonPayload.fields.id` in https://github.com/mozilla/bigquery-etl/pull/1683 because the source FxA auth logs table had a type change (STRING to FLOAT64) between 2021-01-17 and 2021-01-18.

In particular, the field has a different schema between `moz-fx-fxa-prod-0712.fxa_prod_logs.docker_fxa_auth_20210117` and
`moz-fx-fxa-prod-0712.fxa_prod_logs.docker_fxa_auth_20210118`.

I'd like to track down with FxA folks why this changed and whether we can expect incompatibilities like this in the future.

**Comment by jklukas** [comment]
cc @jbuck

**Comment by jbuck** [comment]
Filed a support ticket for Google: https://console.cloud.google.com/support/cases/detail/26676058?project=moz-fx-fxa-prod-0712

**Comment by jbuck** [comment]
An update from the support ticket:

> While I am not an expert in BQ, I have collaborated with one of our BQ engineers who has confirmed that the likely reason for the change in type is because the first log that was exported set the type for that field when the table was created.
> 
> In our documentation [1], it states:
> 
> "The first exported log entry determines the schema for the destination BigQuery table. The log entry generates a table whose columns are based on the log entry's fields and their types. If new fields appear in subsequent log entries, the table schema is updated. However, if the value type changes for an existing field, then newer log entries that don't match the schema are dropped."
> 
> Following the details covered in 'Schema naming rules' [2], there is an example which shows how the types are specified in an exported log. If a type is not specified, the first entry inserted will set the type for that particular field.
> 
> 1] https://cloud.google.com/logging/docs/export/bigquery#mismatch
> [2] https://cloud.google.com/logging/docs/export/bigquery#schema_naming_rules 

I manually deleted the empty table `moz-fx-fxa-prod-0712:fxa_prod_logs.docker_fxa_auth_20210130` and then recreated it with `jsonPayload.fields.id` typed as a STRING. I believe this should resolve the error, lets check on Monday

**Comment by jbuck** [comment]
@jklukas I think this worked fine over the weekend. Do you want to convert the older tables column types back to string, so that you can revert your patch? Or just leave it as-is?

**Comment by jklukas** [comment]
I tested the query, and it looks like it now works again with the patch removed.

But if we just remove the patch now, we will likely hit an issue in ~80 days. When we do a wildcard query, the first matching table is used to set the schema for the result. Right now, that schema has a string. But once old tables roll off, we'll eventually get to a point where the first matching table is one with the FLOAT64 type, at which point the query will break again.

So, we can leave the patch in place and eventually revert it in late April. Or else we need to recreate all the affected tables, which is probably somewhat difficult.

I don't know that this field gets used, so I think it's fine to leave as-is.

**Comment by jklukas** [comment]
And thanks for following up and figuring out what happened 🥳

**Comment by jklukas** [comment]
For future reference, this query is the minimal reproduction of the problem:

```
select 
  cast(jsonPayload.fields.id as string),
  count(*)
  FROM
    `moz-fx-fxa-prod-0712.fxa_prod_logs.docker_fxa_auth_2021011*`
    where _table_suffix = '0'
group by 1 order by 2 desc
```

Once the shard for 2021-01-29 rolls off, we'll be able to revert the patch.

**Comment by jbuck** [comment]
I think I can change the column types using something like the following query:

```
SELECT
  * REPLACE (
    (
      SELECT AS STRUCT
        jsonPayload.* REPLACE (
          (
            SELECT AS STRUCT
              jsonPayload.fields.* REPLACE (
                CAST(NULL AS STRING) AS id
              )
          ) AS fields
        )
    ) AS jsonPayload
  )
FROM
  -- do this for 20210119 to 20210129 inclusive
  `moz-fx-fxa-prod-0712.fxa_prod_logs.docker_fxa_auth_20210119`
```

Thoughts?

**Comment by jklukas** [comment]
Yes, that would be great! In that case, we can actually carry over the values by using `FORMAT("%.0f", id) AS id` since we know the value will be a float on the target days.

**Comment by jbuck** [comment]
> Yes, that would be great! In that case, we can actually carry over the values by using `FORMAT("%.0f", id) AS id` since we know the value will be a float on the target days.

I wonder if it'd be better to leave the value as null, because the `id` value will only be present for log lines that have a uid consisting entirely of numbers, and since it's a float the uid will be truncated, right?

**Comment by jklukas** [comment]
> I wonder if it'd be better to leave the value as null, because the id value will only be present for log lines that have a uid consisting entirely of numbers, and since it's a float the uid will be truncated, right?

I haven't thought too deeply about what the possible values for `id` are. If it's the case that we expect many of them were written as nulls anyway, then no values for these days is probably easier to reason about than partially present values. Leaving these all as null strings for the affected days is fine by me.

**Comment by jbuck** [comment]
@jklukas I've changed the column type on all of the tables, and your minimal test case now runs correctly

**Comment by jklukas** [comment]
Thank for following up on this, @jbuck. The changes look effective from my tests, too. I've filed a PR to remove the special handling.
