### ISSUE TITLE
CI dry-run and views publishing failure: telemetry_derived.scalar_percentiles_v1 was not found in location US

### ISSUE THREAD

**Issue by whd** [mozilla/bigquery-etl#1698]
`google.api_core.exceptions.NotFound: 404 Not found: Table moz-fx-data-shared-prod:telemetry_derived.scalar_percentiles_v1 was not found in location US`

I saw this when merging https://github.com/mozilla/bigquery-etl/pull/1697 but opted to merge it anyway since it appears unrelated and getting copy-dedup to work was a priority.

```
 [{'code': 404, 'errors': [{'message': 'Not found: Table moz-fx-data-shared-prod:telemetry_derived.scalar_percentiles_v1 was not found in location US', 'domain': 'global', 'reason': 'notFound'}], 'response': {'headers': {'alt-svc': 'h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'cache-control': 'private', 'content-encoding': 'gzip', 'content-type': 'application/json; charset=UTF-8', 'date': 'Thu, 21 Jan 2021 01:32:09 GMT', 'server': 'ESF', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '0'}}, 'message': 'Not found: Table moz-fx-data-shared-prod:telemetry_derived.scalar_percentiles_v1 was not found in location US'}]
```

**Comment by acmiyaguchi** [comment]
See https://github.com/mozilla/bigquery-etl/issues/1660#issuecomment-764016741 for the reason, this shouldn't be a problem going forward.

**Comment by acmiyaguchi** [comment]
If you closely inspect the results of another dry run (albeit one that failed due to intermittent timeout), it shows that this no longer an issue. In particular, moz-fx-data-shared-prod:telemetry_derived.scalar_percentiles_v1 referenced by clients_probe_counts_v1 now exists because of the most recent DAG run.
