### ISSUE TITLE
Dry runs failing due to experiment_search_aggregates_v1

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#1723]
CI is failing for this repo right now due to the following dry run failure:

> sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_v1/query.sql ERROR
> [{'code': 400, 'errors': [{'message': 'Unrecognized name: submission_date at [6:3]', 'domain': 'global', 'reason': 'invalidQuery', 'location': 'q', 'locationType': 'parameter'}], 'response': {'headers': {'alt-svc': 'h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'cache-control': 'private', 'content-encoding': 'gzip', 'content-type': 'application/json; charset=UTF-8', 'date': 'Wed, 27 Jan 2021 15:19:37 GMT', 'server': 'ESF', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '0'}}, 'message': 'Unrecognized name: submission_date at [6:3]'}]

cc @scholtzan

**Comment by scholtzan** [comment]
I updated the schema for `experiment_search_aggregates_v1` in preparation of https://github.com/mozilla/bigquery-etl/pull/1721. The changes there should fix this.
