### ISSUE TITLE
Provide a high-level description of bigquery-etl

### ISSUE THREAD

**Issue by Iinh** [mozilla/bigquery-etl#1757]
Right now we're generating content for derived datasets in UDFs, while things are slowly coming together, we're still missing a high-level description of this repository to provide a wider-view understanding.

@wlach suggested that this should be a few paragraphs long of the "what/why". 
(This is partly inspired by @harterrt's [blog post](https://blog.harterrt.com/lit-review.html), and [Divio's documentation guide](https://documentation.divio.com/))

**Comment by kik-kik** [comment]
@Iinh Just to make sure I understand the request, is the suggestion to include more information regarding this tool and what its purpose/usage is inside README.md or some other place within the repo?
