### ISSUE TITLE
Improve Markdown processing in generated docs

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#1764]
I merged https://github.com/mozilla/bigquery-etl/pull/1755 to add descriptions for several desktop views, and I see the results reflected now in the generated docs.

The output looks to correctly render items in backticks as `code`, but newlines aren't behaving as I expect. I see one long running paragraph where I would expect to see a few linebreaks.

In particular, yaml like the below (using `>-`) should render a newline in the output where there's a black line in the input:

```
description: >-
  Captures history of activity of each client in 28 day
  windows for each submission date.

  There will be one row per client per `submission_date`. A given client will
  stop appearing for new dates if they do not send a `main` ping for 28 days.
```

There's also a link that's not correctly rendered, but I think that was my fault for breaking the link across two lines, which may not be valid.

cc @Iinh

**Comment by Iinh** [comment]
I did a bit of research and [this resource](https://yaml-multiline.info/) says that `>-` replaces newlines with spaces, and strips new lines at block end. So the markdown output was rendered correctly. To preserve line breaks I think we need to use `|-` instead. I'll go in these files and change `>-` to `|-`, and will also fix the link issue.

**Comment by jklukas** [comment]
You explanation makes total sense to me now. I concur that using `|-` sounds like the right way forward.
