### ISSUE TITLE
UDF for sortable version parsing

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#1770]
From discussion on Slack:

> For example, we'll release Firefox v100 early next year and truncate_version(app_version, 'minor') > 80 would evaluate false for pings with an app_version of 100.x. I think with semantic versioning (afaik we use for all products), casting major and major.minor to a numeric should work as expected.

**Comment by jklukas** [comment]
cc @wlach @ecsmyth

**Comment by wlach** [comment]
Since the `truncate_version` UDF *just* landed, I am tempted to break its API and make it return a float, since I think that should work in all the cases we care about. Any thoughts?

**Comment by jklukas** [comment]
I think a reasonable way forward here might be to make a function that returns a struct. So `mozfun.norm.semantic_version("102.12.13-beta")` function that returns a struct:

```
major: 102 (int)
minor: 12 (int)
patch: 13 (int)
suffix: "-beta" (string)
major_minor: 102.12 (float)
```

**Comment by jklukas** [comment]
I'm a little leery of using a float to represent major+minor version. Semantically, it should be an array of integers. A float certainly allows for more ergonomic sorting, but a float may be unstable if used as a grouping key.

**Comment by jklukas** [comment]
> Since the truncate_version UDF just landed, I am tempted to break its API and make it return a float, since I think that should work in all the cases we care about. Any thoughts?

To be clear, I don't want to block this change. @ecsmyth points out some clear usability problems of the string version, and there's a path here to make it nicely sortable by changing the return type to float.

I would just want to see some tests that show we don't end up with "12.3" becoming 12.30000000000000004, etc.

**Comment by ecsmyth** [comment]
@jklukas I like your struct-based approach. The name ties it to a specific versioning scheme and it is flexible enough for a few different use cases. I think that being unable to use the returned value to group or in a `SELECT DISTINCT` is ok, since I'd image you'd be operating on a field of the struct rather than the struct itself.

**Comment by wlach** [comment]
> > Since the truncate_version UDF just landed, I am tempted to break its API and make it return a float, since I think that should work in all the cases we care about. Any thoughts?
> 
> To be clear, I don't want to block this change. @ecsmyth points out some clear usability problems of the string version, and there's a path here to make it nicely sortable by changing the return type to float.
> 
> I would just want to see some tests that show we don't end up with "12.3" becoming 12.30000000000000004, etc.

I took this approach in #1772. I believe using NUMERIC should protect us against that pathological case. 

We can keep this issue open for implementing the larger thing you mention.

**Comment by ANich** [comment]
We now have a udf that does this - `mozfun.norm.browser_version_info`, albeit now with new problems 🥲 see 
https://github.com/mozilla/bigquery-etl/issues/2917
https://github.com/mozilla/bigquery-etl/issues/3664
