### ISSUE TITLE
UDF that points at the most recent successful ETL date

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#1800]
This UDF would simply return a `DATE`, that is usually pointing to yesterday. The date would only be updated when all ETL for the day has completed, such that this query is always successful:
```
SELECT *
FROM $table
WHERE submission_date = mozfun.etl.last_updated()
LIMIT 100
```

The difficult part here is determining that relevant ETL has finished. If we assume that ETL includes just queries running in this repository, we could:
- Create a script that checks to see if all tables have $date, and run it every 5 minutes in Airflow
- Create a new task that updates the UDF downstream from all other tasks
- ...others?

Note this would be useful in Looker. We could define small, hidden explores that point to the most recently updated date, and use those for the [suggest explores](https://docs.looker.com/reference/field-params/suggest_explore) (then they are fast and up-to-date).

**Comment by jklukas** [comment]
> WHERE submission_date = mozfun.etl.last_updated()

We should do a sanity check to make sure that BQ is able to take advantage of the date filter when a UDF call is involved. I think it'll work.

> Create a script that checks to see if all tables have $date, and run it every 5 minutes in Airflow

This should be feasible with a query to INFORMATION_SCHEMA, but it may be difficult to prune the results to just tables we expect to be updated daily. There are likely some weird outlier cases to account for.

**Comment by tdsmith** [comment]
I thought I had a use case for this yesterday; I think it's useful when mixing live data and ETL'd data for dashboards running outside of Airflow (in e.g. redash) to understand how far back to reach from the latter.

**Comment by fbertsch** [comment]
Alright, I'm going to try to tackle this with a stored procedure.

**Comment by fbertsch** [comment]
Alex [added this](https://github.com/mozilla/lookml-generator/pull/615)! Done using `INFORMATION_SCHEMA` 🎉
