### ISSUE TITLE
Add "deprecated" boolean to metadata.yaml

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#1827]
As we move towards publishing documentation about views into derived data, it could be very helpful to be able to annotate some views as deprecated. For example, we have a general policy of having user-facing views be unversioned, but we have many views that are duplicated to versioned and unversioned names for historical reasons. It would be great to be able to  hide the views that we consider deprecated, or at least deemphasize them in our generated documentation.

We often need to keep deprecated views around so as to not break existing queries, but I'd like to see us lessen the impact of an ever-growing number of views for users to sort through.

**Comment by ANich** [comment]
This was implemented in https://github.com/mozilla/bigquery-etl/pull/4213. We discussed this briefly during a recent infra meeting and as I understand it the semantics underlying the deprecation flag were built with tables in mind but should apply to views as well, so I think it's fair to close this. I'll likely be testing this soon with `telemetry.clients_daily_v6` https://github.com/mozilla/bigquery-etl/pull/4660. 

cc fysa @alekhyamoz @whd
