### ISSUE TITLE
Generated docs links contain `tmp/generated-sql` in paths

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#1833]
After https://github.com/mozilla/bigquery-etl/pull/1819 was merged, we now see all the generated views, which is great!

The links to GitHub now contain `tmp/generated-sql` in the path names. For example, the [vrbrowser.baseline docs](https://mozilla.github.io/bigquery-etl/mozdata/org_mozilla_vrbrowser/#baseline) contain a link to https://github.com/mozilla/bigquery-etl/blob/master//tmp/generated-sql/sql/moz-fx-data-shared-prod/org_mozilla_vrbrowser/baseline

The links contain `/blob/master//tmp/generated-sql/sql` which probably now needs to be `/blob/generated-sql/sql`, so they look at the generated-sql branch under top-level directly `sql`.

I believe we can sidestep the `tmp/` path problem by copying `/tmp/generated-sql` into place as in https://github.com/mozilla/bigquery-etl/pull/1830

cc @Iinh

**Comment by Iinh** [comment]
Another unexpected problem, sorry for not catching this! I'm going to use your approach in #1830 and update the links accordingly.
