### ISSUE TITLE
Dry run failing on org_mozilla_mozregression_derived/mozregression_aggregates_v1/init.sql

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#1836]
See https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/8210/workflows/fd478802-0847-4ddc-a4d3-c44abd8ea75a/jobs/46472

> sql/moz-fx-data-shared-prod/org_mozilla_mozregression_derived/mozregression_aggregates_v1/init.sql ERROR
 [{'code': 400, 'errors': [{'message': 'moz-fx-data-shared-prod:org_mozilla_mozregression_derived.mozregression_aggregates_v1 is not allowed for this operation because it is currently a VIEW.', 'domain': 'global', 'reason': 'invalid'}], 'response': {'headers': {'alt-svc': 'h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'cache-control': 'private', 'content-encoding': 'gzip', 'content-type': 'application/json; charset=UTF-8', 'date': 'Wed, 24 Feb 2021 14:34:12 GMT', 'server': 'ESF', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '0'}}, 'message': 'moz-fx-data-shared-prod:org_mozilla_mozregression_derived.mozregression_aggregates_v1 is not allowed for this operation because it is currently a VIEW.'}]

cc @wlach @scholtzan

**Comment by wlach** [comment]
@scholtzan I guess we need to change this file to reference `mozilla-public-data` instead of shared-prod?

https://github.com/mozilla/bigquery-etl/blob/master/sql/moz-fx-data-shared-prod/org_mozilla_mozregression_derived/mozregression_aggregates_v1/init.sql

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1694447

**Comment by wlach** [comment]
Strangely enough the Airflow DAG seems to be updating things fine: https://workflow.telemetry.mozilla.org/tree?dag_id=bqetl_internal_tooling even though the query also references the wrong project (?):

https://github.com/mozilla/bigquery-etl/blob/master/sql/moz-fx-data-shared-prod/org_mozilla_mozregression_derived/mozregression_aggregates_v1/query.sql

We might just want to fold this into the above bug, now that I think about it.

**Comment by scholtzan** [comment]
I pushed a fix in https://github.com/mozilla/bigquery-etl/pull/1837 to reference `mozilla-public-data` in the `init.sql` file.

The query itself is correct and doesn't need to be changed. It does reference the `moz-fx-data-shared-prod.org_mozilla_mozregression.usage` table to query data from it which is fine. And even though it is part of the `moz-fx-data-shared-prod` directory, if the `public_bigquery` flag is set in the metadata, results will be written to `mozilla-public-data` when running the query.
