### ISSUE TITLE
Generate docs for moz-fx-data-marketing-prod

### ISSUE THREAD

**Issue by Iinh** [mozilla/bigquery-etl#1864]
We already generated docs for mozdata (`moz-fx-data-shared-prod`) and `mozfun`, the only project left is `moz-fx-data-marketing-prod`.

**Comment by ANich** [comment]
`moz-fx-data-marketing-prod` doesn't have UDFs or stored procedures, and we don't publish dataset docs anymore(https://github.com/mozilla/bigquery-etl/pull/4657). I think we can close this.
