### ISSUE TITLE
Broken links because stable datasets are not available in generated-sql/sql

### ISSUE THREAD

**Issue by Iinh** [mozilla/bigquery-etl#1866]
Currently, we're linking the reference tables to the source folder in `generated-sql/sql`. However, we are getting [404 error](https://github.com/mozilla/bigquery-etl/blob/generated-sql/sql/moz-fx-data-shared-prod/eng_workflow_stable) for `*_stable` datasets, because they are not available in the source directory. 

For example: 

https://mozilla.github.io/bigquery-etl/mozdata/activity_stream/#events
https://mozilla.github.io/bigquery-etl/mozdata/eng_workflow/#bmobugs
![CleanShot 2021-03-02 at 08 35 30@2x](https://user-images.githubusercontent.com/28797553/109682152-ff7e9880-7b32-11eb-826f-93b96bc438ab.png)

cc/ @jklukas

**Comment by jklukas** [comment]
Likely it would be good in this case to simply not make these links. Or if we want to be really ambitious we could link to the source schemas in `mozilla-pipeline-schemas`, which would require some processing of the dataset/table/version name to infer the corresponding namespace/doctype/version for the MPS path.

**Comment by ANich** [comment]
These docs aren't generated anymore (https://github.com/mozilla/bigquery-etl/pull/4657)
