### ISSUE TITLE
CDOU column in firefox_desktop_usage_2021 appears to be wrong

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/bigquery-etl#1871]
See [this query](https://sql.telemetry.mozilla.org/queries/78447/source)

This should be a cumulative sum of DAU for the year up until `submission_date`. 

I believe the problem might be here: 

https://github.com/mozilla/bigquery-etl/blob/404abcae10bf0deee1c4c2ff086fc457cef420bd/sql/moz-fx-data-shared-prod/telemetry_derived/firefox_desktop_usage_v1/query.sql#L5-L17

I think we may need to add a `ORDER BY submission_date` in the window frame.

**Comment by jklukas** [comment]
I think you are entirely right. I will fix this up right now.
