### ISSUE TITLE
Add new profile counts to nondesktop_exact_mau and dependent tables

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/bigquery-etl#1954]
We now have a `first_seen_date` field for mobile products. We will be using this to count daily new profiles.

I think the best way to do this is to change [firefox_nondesktop_exact_mau28_v1](https://github.com/mozilla/bigquery-etl/blob/9bca48821a8a0d40b1700cc14ecd8068d132ed06/sql/moz-fx-data-shared-prod/telemetry_derived/firefox_nondesktop_exact_mau28_v1/query.sql) and add something like `COUNTIF(submission_date = first_seen_date) AS new_profiles)`.

And then we'd ultimately want to pass that through to [mobile_usage_v1](https://github.com/mozilla/bigquery-etl/blob/9bca48821a8a0d40b1700cc14ecd8068d132ed06/sql/moz-fx-data-shared-prod/telemetry_derived/mobile_usage_v1/query.sql) which is powering our looker KPI dashboards.

**Comment by irrationalagent** [comment]
it looks like nondesktop_clients_last_seen does not have first_seen_date yet either, so we would need to add it there first before doing above.

**Comment by jklukas** [comment]
I think we should create an entirely new table to support this. `nondesktop_clients_last_seen` walks a weird line between legacy telemetry and Glean, and I would argue that it treats core pings as the first-class citizen, with Fenix shoehorned in. Specifically, it uses core pings for iOS data.

There's also an awkward translation layer from `firefox_nondesktop_exact_mau28_v1` to `mobile_usage_v1` where we infer the new standard `app_name` values from the _ad hoc_ product names that were used for `firefox_nondesktop_exact_mau28_v1`.

Now that we have first_seen_date in Glean baseline ETL, we should create a `mobile_usage_v2` table that's Glean-first, and only pulls in core pings where necessary (probably only for Fennec).

The piece that I see as blocking this is the Firefox for iOS situation. We have up to this point been using core pings for KPI reporting, GUD, etc. We still don't have a migration-type ping to allow us to correlate core pings to Glean pings. Given that we're in Q2 now, I think we have to make the decision as to whether we continue to use core pings for iOS for the rest of 2021, or if we're going to switch to Glean pings and not be able to track the core-to-Glean transition.

**Comment by jklukas** [comment]
@irrationalagent - Do we know the final list of mobile apps that we want to count for 2021? Does the table in https://mozilla.github.io/bigquery-etl/mozfun/norm/#product_info-udf match reality, or are we considering only Fenix+Fennec, Firefox for iOS, and Focus?

**Comment by irrationalagent** [comment]
We are only tracking KPIs for:
- Firefox for Android (Fennec + Fenix)
- Firefox for iOS
- Firefox Focus for Android (this is core ping only)
- Firefox Focus for iOS

**Comment by jklukas** [comment]
Filed https://github.com/mozilla/bigquery-etl/pull/1957 to update the table of 2021 apps contributing to mobile KPI.

**Comment by jklukas** [comment]
cc @acmiyaguchi

**Comment by jklukas** [comment]
@irrationalagent has started a document to discuss options for the iOS situation going forward.

Given that any timeline for having linkage between core pings and Glean telemetry for iOS will be months out, I'm backing away from my suggestion in https://github.com/mozilla/bigquery-etl/issues/1954#issuecomment-818741384.

Instead, I think we should unblock this immediate need by investing a bit more in core ping ETL, applying the same treatment as we gave baseline-based ETL:

- Add `first_seen_date` via join and `is_new_profile` to core_clients_daily query; do a one-off join query to backfill these fields
- Propagate `first_seen_date` to `core_clients_last_seen` (no query change should be necessary); backfill via one-off query
- Update `nondesktop_clients_last_seen` and `mobile_usage_v1` to expose the `first_seen_date` as per @irrationalagent's original request

**Comment by jklukas** [comment]
This was implemented in #1962
