### ISSUE TITLE
core_clients_last_seen does not have updated first seen date

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/bigquery-etl#2056]
See https://sql.telemetry.mozilla.org/queries/80137/source

The last time the first seen date in the clients last seen table was updated was 2021-04-04. This is almost certainly incorrect.

**Comment by jklukas** [comment]
This task is running daily, but perhaps it's having no effect: https://workflow.telemetry.mozilla.org/log?task_id=telemetry_derived__core_clients_first_seen__v1&dag_id=copy_deduplicate&execution_date=2021-05-20T01%3A00%3A00%2B00%3A00

**Comment by acmiyaguchi** [comment]
It looks like the source of this issue is that the core clients first seen hasn't been updated since 2021-04-04: https://sql.telemetry.mozilla.org/queries/80138/source

**Comment by acmiyaguchi** [comment]
It looks like the airflow logs show the core_clients_first_seen job failing silently:

```
RUNNING\r                                                                                      
\rWaiting on bqjob_r56fde488d9e4cec1_000001798c79156e_1 ... (1s) Current status: RUNNING\r                                                                                      
\rWaiting on bqjob_r56fde488d9e4cec1_000001798c79156e_1 ... (2s) Current status: RUNNING\r                                                                                      
\rWaiting on bqjob_r56fde488d9e4cec1_000001798c79156e_1 ... (3s) Current status: RUNNING\r                                                                                      
\rWaiting on bqjob_r56fde488d9e4cec1_000001798c79156e_1 ... (4s) Current status: RUNNING\r                                                                                      
\rWaiting on bqjob_r56fde488d9e4cec1_000001798c79156e_1 ... (4s) Current status: DONE   \n'
[2021-05-21 01:10:22,857] {pod_launcher.py:156} INFO - b'INFO: No metadata.yaml found for {} sql/moz-fx-data-shared-prod/telemetry_derived/core_clients_first_seen_v1/query.sql\n'
```

**Comment by jklukas** [comment]
I don't think it's a silent failure. It's running to completion very quickly and producing no output. I'm able to find the job, and the result set is empty.

**Comment by acmiyaguchi** [comment]
The use of `submission_date` for the date partition may be problematic; I'll put in a PR for that field. Otherwise, I'll write some unit tests for the query and see if I can debug the issue.

**Comment by jklukas** [comment]
More proof that the query is running, is that we can see the empty partitions in information schema: https://sql.telemetry.mozilla.org/queries/80140/source

**Comment by acmiyaguchi** [comment]
This probably indicates issues with the query then. I ran the query replacing `@submission_date` with 2021-05-20 and got 0 results: https://sql.telemetry.mozilla.org/queries/80141/source. I'll write some tests and try to update the query.

**Comment by acmiyaguchi** [comment]
I ran backfill for this table in two parts:

```
bqetl query backfill telemetry_derived.core_clients_first_seen_v1  --project_id=moz-fx-data-shared-prod --time_partitioning_field=first_seen_date -s 2021-04-04 -e 2021-04-06

bqetl query backfill telemetry_derived.core_clients_first_seen_v1  --project_id=moz-fx-data-shared-prod --time_partitioning_field=first_seen_date -s 2021-04-06 -e 2021-05-23
```

The new options on the backfill command to accept generalized parameters and parallelization is excellent.

**Comment by acmiyaguchi** [comment]
I'll be running the backfill in https://github.com/mozilla/bigquery-backfill/tree/main/backfill/2021-04-20-mobile-first-seen-date tomorrow.

@jklukas to confirm, are all of the queries in the backfill relevant here?

**Comment by jklukas** [comment]
Those queries won't work without modification because the core_clients_daily and last_seen tables now have first_seen_date already integrated, whereas the 04-20 backfill was adding those fields to the schema.

I think it makes sense to follow the same general process, adding `EXCEPT (first_seen_date)` as appropriate to get the queries working.

We may also want to run queries to backfill first_seen_date for the fenix and ios baseline_clients_* tables, which isn't captured here.

**Comment by acmiyaguchi** [comment]
Issues have propagated themselves into downstream tables, which should be resolved by backfill. https://bugzilla.mozilla.org/show_bug.cgi?id=1712790

**Comment by acmiyaguchi** [comment]
Backfill has been performed. The baseline_clients_daily tables between April and May have not been updated. The effect of migrations is expected to be small and exploration of the mobile usage queries shows that new profile counts do not differ heavily from the original counts (with missing core first seen profiles now appearing). However, the baseline clients first seen table may always be joined against the last seen table to get up to date profile information.
