### ISSUE TITLE
Add UDF for mapping apple store storefronts to country codes in static table

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/bigquery-etl#2068]
The apple storefront table reports countries names that do not match the static table with country names and country codes. It also does not report country codes. To work around this restriction, some manual modifications are necessary for a complete join. See this query:

https://github.com/mozilla/looker-spoke-default/blob/35ee89552f86aa495ec5a31c017bb907521b5258/duet/views/mobile_ios_country.view.lkml#L33-L105

See `moz-fx-data-marketing-prod.apple_app_store.metrics_by_storefront` and `mozdata.static.country_codes_v1`

**Comment by jklukas** [comment]
My preference here would be to update https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/static/country_names_alternate.csv to include these extra names, mapping them to iso codes. Then we'd do a join from `metrics_by_storefront` to `country_names_v1` to get the code, and then a join to `country_codes` to get the normalized country name.

We can also update the logic to include a `standard_country_name` field in the `country_names_v1` table to avoid having to do the second join.

**Comment by acmiyaguchi** [comment]
This seems like a reasonable path forward, I wasn't aware that we had a table made specifically for these cases.

**Comment by acmiyaguchi** [comment]
https://sql.telemetry.mozilla.org/queries/80165/source

Query for the names that need alternatives.
