### ISSUE TITLE
Dry runs failing on main due to mozilla_vpn_derived/retention_by_subscription_v1

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#2172]
[Example failure](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/10060/workflows/1222d8f7-8fcc-4af4-953a-2b6b2e49e0ff/jobs/63999?invite=true#step-104-896)

> Schema defined in sql/moz-fx-data-shared-prod/mozilla_vpn_derived/retention_by_subscription_v1/schema.yaml incompatible with query sql/moz-fx-data-shared-prod/mozilla_vpn_derived/retention_by_subscription_v1/query.sql

**Comment by jklukas** [comment]
cc @relud

**Comment by relud** [comment]
i'm out sick, @acmiyaguchi can you update the schema in that file to match the table?
