### ISSUE TITLE
Script for creating default views

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#218]
As part of the accepted [BQ Layout and Table Structure Proposal](https://github.com/mozilla/bigquery-etl/issues/189), we will be hiding tables from users in the telemetry_raw and other `<namespace>_raw` datasets in shared-prod, and providing user-facing views in the `telemetry` dataset.

It is becoming difficult to manage this by hand, so we need to start automating it. A first step could be a script in this repository that lists tables in the shared-prod `*_raw` datasets, and generates simple `CREATE VIEW namespace.foo AS SELECT * FROM namespace_raw.foo_<highest_version_number>` files in the `templates` directory wherever they are missing. We could then run this offline, prune and adjust the contents by hand, and commit the results.

Depends on https://github.com/mozilla/bigquery-etl/issues/189

**Comment by relud** [comment]
see also #226
