### ISSUE TITLE
Generate a deploy preview of sql generated by bigquery-etl

### ISSUE THREAD

**Issue by wlach** [mozilla/bigquery-etl#2273]
For testing/validation purposes, it would be really nice if we generated a tarball of all the sql generated by bigquery-etl in the netlify deploy preview in addition to the documentation (so you can download it and manually inspect it).

For even more bonus points, we could also generate a diff of that sql vs. production for manual inspection.

**Comment by jklukas** [comment]
We now have a diff generated on each PR per work by @scholtzan
