### ISSUE TITLE
Generate docs for all UDFs

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/bigquery-etl#228]
We should have a reference page for all the persistent UDFs, and we're much more likely to keep the docs consistent if the documentation lives in docstrings with the code. We'll need to add a build step that auto-generates docs and submits a PR to DTMO if there are changes.

**Comment by jklukas** [comment]
I had imagined generating docs and hosting via GitHub Pages, then linking to that from DTMO, but if generating PRs to DTMO is feasible, that would be even better.

**Comment by jklukas** [comment]
There's renewed interest in usability of UDFs (see #969) and given recent work by @wlach to narrow the focus of DTMO, I think the right thing to do is to generate UDF docs via GitHub Pages, or even just as a static README in this repo.

**Comment by wlach** [comment]
> There's renewed interest in usability of UDFs (see #969) and given recent work by @wlach to narrow the focus of DTMO, I think the right thing to do is to generate UDF docs via GitHub Pages, or even just as a static README in this repo.

I've been spitballing the idea of creating a more user-friendly web-based interface to the UDFs and tables generated by bigquery-etl, but I think generating a static markdown file would be a great way to start. Can always expand later.

**Comment by wlach** [comment]
@scholtzan implemented this in #1102, as mentioned above we opted not to put this on docs.tmo. See also: mozilla/data-docs#583
