### ISSUE TITLE
Main branch failing `deploy` task due to mvn error

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#2287]
It looks like we have not had a successful run of the `deploy` task for this repo in about a week, failing with a maven error while building the docker image. Strangely, the `deploy-to-private-gcr` task (which also has to build the image) works.

I notice that the docker build is using cache up until the failing `RUN mvn dependency:copy-dependencies` invocation, so perhaps there's something bad in the docker layer cache?

The error is:

```
Step 12/23 : RUN mvn dependency:copy-dependencies
 ---> Running in 2efdc878229b
ls: cannot access '/usr/bin/mvn': Operation not permitted
Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.classworlds.launcher.Launcher
The command '/bin/sh -c mvn dependency:copy-dependencies' returned a non-zero code: 1
```

cc @relud

**Comment by jklukas** [comment]
I've confirmed that dockerhub shows the image as 7 days old: https://hub.docker.com/r/mozilla/bigquery-etl

cc @whd - Jenkins likely is not triggering deploys on bigquery-etl code updates, since we're never pushing the changes to dockerhub.

**Comment by whd** [comment]
> I've confirmed that dockerhub shows the image as 7 days old: https://hub.docker.com/r/mozilla/bigquery-etl
> 
> cc @whd - Jenkins likely is not triggering deploys on bigquery-etl code updates, since we're never pushing the changes to dockerhub.

This sounds accurate, and explains why https://github.com/mozilla/bigquery-etl/issues/2214 only errored on a schemas deploy instead of soon after it was merged.
