### ISSUE TITLE
Circular references in bigquery_etl.glean_usage.GleanAppPingViews

### ISSUE THREAD

**Issue by scholtzan** [mozilla/bigquery-etl#2290]
This was possibly introduced in https://github.com/mozilla/bigquery-etl/pull/2271

I noticed that for `firefox_desktop`, view definitions reference themselves. For example:
https://github.com/mozilla/bigquery-etl/blob/generated-sql/sql/moz-fx-data-shared-prod/firefox_desktop/metrics/view.sql

I'm guessing there is some problem with the app name and the glean dataset name being the same.

cc @wlach

**Comment by wlach** [comment]
> This was possibly introduced in #2271
> 
> I noticed that for `firefox_desktop`, view definitions reference themselves. For example:
> https://github.com/mozilla/bigquery-etl/blob/generated-sql/sql/moz-fx-data-shared-prod/firefox_desktop/metrics/view.sql
> 
> I'm guessing there is some problem with the app name and the glean dataset name being the same.
> 
> cc @wlach

Ah yes, we should probably skip generating ping views for these types of applications. Should be a straightforward change.

**Comment by whd** [comment]
It looks like this hasn't propagated to private-bigquery-etl's generated-sql branch, possibly due to https://github.com/mozilla/bigquery-etl/issues/2287.
