### ISSUE TITLE
Write a plan for moving all generated content out of `main`

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#2313]
Per https://github.com/mozilla/bigquery-etl/pull/2307 we currently have a few different approaches to query generation coexisting in this codebase, which causes some confusion.

The ideal state is to have no generated code check into `main`, relying on CI to populate generated content in the `generated-sql` branch. But there are several realities today preventing that.

Chiefly, we run DAG generation separately from sql generation, which means that generated queries can't be included in the generated DAGs. We could consider moving DAG generation after SQL generation, but this may lead to overly long build times.

Similarly, our testing framework for exercising queries assumes that queries are checked in to `main`.

A proposal is needed here to figure out the full scope of changes needed to support a good workflow that pushes all SQL generation to CI.

**Comment by scholtzan** [comment]
I started putting a proposal together: https://docs.google.com/document/d/1k9Gv_zJyWAVDhuR8vkEizDxfko35jyU6Shb4EPsBfzs/edit#

**Comment by scholtzan** [comment]
Implementing the proposal will be broken out in the following steps (separate PRs):
- [ ] Move query generators out of `bigquery_etl/` into `sql_generators/`
- [ ] Update the CI to run the SQL + DAG generation
- [ ] Make changes to show diff when opening a PR
- [ ] Update CLI
- [ ] Remove generated query contents from `main` (until this point the generated queries will simply be overwritten when running the SQL generation, this helps to prevent breakages)
- [ ] Change Airflow DAG sync script to pick up generated DAGs from the `generated-sql` branch
- [ ] Remove generated DAGs from `main`
- [ ] Add support for testing generators
