### ISSUE TITLE
validate-views currently fails on main due payload_bytes_decoded_all

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#2370]
Example failing task: https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/11118/workflows/a503ab9d-cba8-4749-84fc-c3c29fc9fafb/jobs/75663

The new payload_bytes_decoded_all view references 3 authorized views, but the CI task appears to not be aware of this, so is trying to run the underlying queries.

**Comment by whd** [comment]
I'm about to authorize the views, so maybe once that's in place it'll work as expected.

**Comment by whd** [comment]
I think this is working as expected now that the authorizations are in place: https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/11118/workflows/9ef9df37-6e0a-4b41-bcae-f41d36842bbc/jobs/75713
