### ISSUE TITLE
monitoring.payload_bytes_decoded_all view header metadata has incorrect values

### ISSUE THREAD

**Issue by whd** [mozilla/bigquery-etl#2514]
I suspect this is some BQ gotcha related to `UNION`s with nested structs.

```sql
SELECT
  metadata.header
FROM
  `moz-fx-data-shared-prod.monitoring.payload_bytes_decoded_all`
WHERE
  DATE(submission_timestamp) = '2021-11-18'
  AND metadata.header.x_telemetry_agent LIKE 'TLS%'
LIMIT
  100
```
has results that include `x_telemetry_agent` having the content of `x_lb_tags` and `x_lb_tags` being `NULL`.

```sql
SELECT
  (
  SELECT
    COUNT(*)
  FROM
    `moz-fx-data-shared-prod.monitoring.payload_bytes_decoded_telemetry`
  WHERE
    DATE(submission_timestamp) = '2021-11-18'
    AND metadata.header.x_telemetry_agent LIKE 'TLS%') + (
  SELECT
    COUNT(*)
  FROM
    `moz-fx-data-shared-prod.monitoring.payload_bytes_decoded_structured`
  WHERE
    DATE(submission_timestamp) = '2021-11-18'
    AND metadata.header.x_telemetry_agent LIKE 'TLS%') + (
  SELECT
    COUNT(*)
  FROM
    `moz-fx-data-shared-prod.monitoring.payload_bytes_decoded_stub_installer`
  WHERE
    DATE(submission_timestamp) = '2021-11-18'
    AND metadata.header.x_telemetry_agent LIKE 'TLS%')
```
returns 0 as expected.

I notice the top-level metadata field order is normalized in e.g. https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/monitoring/payload_bytes_decoded_telemetry/view.sql#L9; is it required to normalize all nested structs as well to get consistent results? This seems pretty annoying.

**Comment by jklukas** [comment]
Yes, I think UNION expects the overall type to match exactly in the unions, but field names are taken only from the first `SELECT` and otherwise the union is done by type and order rather than field name.

**Comment by whd** [comment]
Thanks, for the specific monitoring use case I was planning to use this for (verify GCLB is in permissive mode) I'm going to `SELECT` the specific header and `UNION` across pipeline families only if necessary.
