### ISSUE TITLE
Support updating tables to match metadata.yaml

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#2537]
Related to https://github.com/mozilla/bigquery-etl/issues/2536

We have a `bqetl query schema deploy` command which handles  should have a way to apply changes to metadata.yaml to the table. Some fields, like partitioning, cannot be updated. But other fields like expiration, require_partition_filter, and clustering fields can be changed through a table update operation.

`bqetl query schema deploy` currently calls `client.update_table`, but only passes in the new schema. We could consider having that command also apply options. Or perhaps it should be a new command. I do worry that it could be surprising to have metadata changes propagate via a command called `schema deploy`.

**Comment by jklukas** [comment]
cc @whd @scholtzan

**Comment by scholtzan** [comment]
I think it is fine for `schema deploy` to apply metadata changes. Actually, it already does use some of the metadata, such as clustering and partitioning information, when creating a new table. It might also be more confusing to have separate commands that do similar things.

**Comment by ANich** [comment]
@scholtzan with the changes to `bqetl query schema deploy` and the artifact deployment DAG this is now the case right?

**Comment by scholtzan** [comment]
yes
