### ISSUE TITLE
Create derived dataset for youtube regrets reporter

### ISSUE THREAD

**Issue by jmccrosky** [mozilla/bigquery-etl#2572]
As discussed on slack, we want a dashboard to provide summary metrics for the RegretsReporter data.  The raw data is restricted access, so we want to run an ETL to create a summary table accessible to anyone in Mozilla.  The query should be:

```sql
WITH base_t AS (
    SELECT
        metrics.string.metadata_installation_id AS installation_id,
        DATE(submission_timestamp) as date,
        ANY_VALUE(metrics.string.metadata_experiment_arm) AS experiment_arm,
        ANY_VALUE(metrics.string.metadata_feedback_ui_variant) AS ui_arm,
        ANY_VALUE(metadata.geo.country) AS country,
        ANY_VALUE(metadata.user_agent.browser) AS browser,
        IF(LOGICAL_OR(e.name = "video_recommended"), 1, 0) + (IF(LOGICAL_OR(e.name = "regret_action"), 1, 0) * 2) + (IF(LOGICAL_OR(e.name = "video_played"), 1, 0) * 4) AS activities,
    FROM
        `moz-fx-data-shared-prod.regrets_reporter_ucs_live.main_events_v1`,
        UNNEST(events) e
    WHERE
        submission_timestamp >= "2021-12-2"
    GROUP BY
        metrics.string.metadata_installation_id,
        DATE(submission_timestamp)
),
dau_t AS (
SELECT
    COUNT(DISTINCT installation_id) AS dau,
    date,
    experiment_arm,
    ui_arm,
    country,
    browser,
    activities
FROM
    base_t
GROUP BY
    date,
    experiment_arm,
    ui_arm,
    country,
    browser,
    activities
ORDER BY
    date
),
dates_t AS (
    SELECT
        date AS d
    FROM
        dau_t
    GROUP BY
        date
),
wau_t AS (
    SELECT
        COUNT(DISTINCT installation_id) AS wau,
        d AS date,
        experiment_arm,
        ui_arm,
        country,
        browser,
        activities
    FROM
        dates_t 
    INNER JOIN
        base_t
    ON date BETWEEN DATE_SUB(dates_t.d, INTERVAL 6 DAY) AND dates_t.d
    GROUP BY
        d,
        experiment_arm,
        ui_arm,
        country,
        browser,
        activities
    ORDER BY
        d
),
new_user_base_t AS (
  SELECT
    metrics.string.metadata_installation_id AS installation_id,
    MIN(DATE(submission_timestamp)) as date,
    ANY_VALUE(metrics.string.metadata_experiment_arm) AS experiment_arm,
        ANY_VALUE(metrics.string.metadata_feedback_ui_variant) AS ui_arm,
        ANY_VALUE(metadata.geo.country) AS country,
        ANY_VALUE(metadata.user_agent.browser) AS browser,
        IF(LOGICAL_OR(e.name = "video_recommended"), 1, 0) + (IF(LOGICAL_OR(e.name = "regret_action"), 1, 0) * 2) + (IF(LOGICAL_OR(e.name = "video_played"), 1, 0) * 4) AS activities,
  FROM
    `moz-fx-data-shared-prod.regrets_reporter_ucs_live.main_events_v1`,
    UNNEST(events) e
  WHERE
    submission_timestamp >= "2021-12-2"
  GROUP BY
    installation_id
),
new_user_t AS (
    SELECT
        COUNT(DISTINCT installation_id) AS new_users,
        date,
        experiment_arm,
        ui_arm,
        country,
        browser,
        activities
    FROM
        new_user_base_t
    GROUP BY
        date,
        experiment_arm,
        ui_arm,
        country,
        browser,
        activities
    ORDER BY
        date
)
    SELECT 
        dau,
        wau,
        new_users,
        date,
        experiment_arm,
        ui_arm,
        country,
        browser,
        activities
    FROM
        dau_t
    FULL JOIN
        wau_t
    USING(date, experiment_arm, ui_arm, country, browser, activities)
    FULL JOIN
        new_user_t 
    USING(date, experiment_arm, ui_arm, country, browser, activities)
```

**Comment by wlach** [comment]
Should be possible to schedule this query using the instructions here: https://mozilla.github.io/bigquery-etl/cookbooks/creating_a_derived_dataset/

It doesn't sound like we want to make this a public dataset at this time, so that part can be skipped.

**Comment by kik-kik** [comment]
@wlach what should be target dataset for this result? Should it be `org_mozilla_mozregression_derived` as mentioned in the documentation linked? Would `youtube_regrets_reporter` be a good table name for this table?

**Comment by wlach** [comment]
> @wlach what should be target dataset for this result? Should it be `org_mozilla_mozregression_derived` as mentioned in the documentation linked? Would `youtube_regrets_reporter` be a good table name for this table?

definitely not org_mozilla_mozregression_derived, that's for [mozregression](https://mozilla.github.io/mozregression/) (a different application).

I would say regrets_reporter_derived *would* make sense for a dataset name (it looks like it already exists), except that has restricted access (since the underlying data is sensitive). So maybe we can create a new `regrets_reporter_aggregates` / `regrets_reporter_aggregates_derived` pair of datasets for the views / tables. 

As for the table name, `youtube_regrets_reporter` doesn't really say what the table aggregates. I would come up with a name like `regrets_reporter_stats` or something that's more descriptive.

**Comment by jklukas** [comment]
> I would say regrets_reporter_derived _would_ make sense for a dataset name (it looks like it already exists), except that has restricted access (since the underlying data is sensitive). So maybe we can create a new `regrets_reporter_aggregates` / `regrets_reporter_aggregates_derived` pair of datasets for the views / tables.

I do think `regrets_reporter_derived` is the right place for this. We can set a table-level grant in `metadata.yaml` that opens up access to `mozilla-confidential` (search for `mozilla-confidential` in this repo to find examples). And then do the same for the view in the `regrets_reporter` namespace.

For table name, I'd suggest `regrets_reporter_summary_v1` and view `regrets_reporter_summary`.

**Comment by jklukas** [comment]
We'll need to ping @whd when this is ready, so that he can apply the relevant table grants.

**Comment by jmccrosky** [comment]
Hey, thanks for setting this up, but the table seems to only have data up to 12-16.  Can someone check?

Also, the query references the live tables and probably should reference stable tables.  I didn't know when I created the table that live tables have a one month retention...

**Comment by jklukas** [comment]
> Hey, thanks for setting this up, but the table seems to only have data up to 12-16. Can someone check?

This change was merged and the DAG exists, but looks like it was never switched on. We just need to flip the switch on https://workflow.telemetry.mozilla.org/tree?dag_id=bqetl_regrets_reporter_summary

> Also, the query references the live tables and probably should reference stable tables. I didn't know when I created the table that live tables have a one month retention...

Indeed, we should update the query to use the stable table.

**Comment by kik-kik** [comment]
Table recreated and DAG now executed.
