### ISSUE TITLE
GLAM etl should not catalogue "search" metrics / probes

### ISSUE THREAD

**Issue by wlach** [mozilla/bigquery-etl#2605]
Currently the GLAM ETL catalogues search metrics and probes. For example:

https://glam.telemetry.mozilla.org/firefox/probe/search_counts/explore?process=parent
https://glam.telemetry.mozilla.org/fenix/probe/browser_search_ad_clicks/explore?aggType=avg&app_id=release

These probes are generally not amenable to analysis via GLAM (we have many dedicated derived datasets and looker explores oriented around them). Also, search data is generally considered sensitive and potentially blocks opening up GLAM to the public ([bug 1712353](https://bugzilla.mozilla.org/show_bug.cgi?id=1712353)). I'd suggest just not scraping this information, which has the bonus of hopefully improving ETL times slightly.

There's a couple of approaches we could use here to excluding these probes, depending on product:

* For Firefox for Android and other glean applications, we could use the tag metadata to mark those metrics which have to do with search (Fenix example: https://dictionary.telemetry.mozilla.org/apps/fenix?itemType=metrics&page=1&search=tags%3ASearch). For Fenix, this will be easier when https://github.com/mozilla-mobile/fenix/pull/22954 lands and this metadata can be scraped via the [mozilla schema generator api](https://github.com/mozilla/mozilla-schema-generator).
* For Firefox legacy, we can probably use an allowlist approach (it's hopefully unlikely any non-glean search probes will be added at this point)

**Comment by edugfilho** [comment]
This is being tracked on the GLAM repo.
https://github.com/mozilla/glam/issues/2654
