### ISSUE TITLE
private-generate-sql failing

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#2694]
I believe this is affecting every PR. See [an example](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/12987/workflows/bfa51748-6b38-4a6e-854c-5a3fa687eafd/jobs/98817)

There appear to be many errors about partition filters:

```
moz-fx-data-shared-prod/telemetry/desktop_retention_1_week/query.sql ERROR
 [{'code': 400, 'errors': [{'message': "Cannot query over table 'moz-fx-data-shared-prod.telemetry_derived.clients_last_seen_v1' without a filter over column(s) 'submission_date' that can be used for partition elimination", 'domain': 'global', 'reason': 'invalidQuery', 'location': 'q', 'locationType': 'parameter'}], 'response': {'headers': {'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'cache-control': 'private', 'content-encoding': 'gzip', 'content-type': 'application/json; charset=UTF-8', 'date': 'Mon, 31 Jan 2022 18:34:58 GMT', 'server': 'ESF', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '0'}}, 'message': "Cannot query over table 'moz-fx-data-shared-prod.telemetry_derived.clients_last_seen_v1' without a filter over column(s) 'submission_date' that can be used for partition elimination"}]
```

**Comment by scholtzan** [comment]
It might be worth checking whether https://github.com/mozilla/bigquery-etl/commit/c1925039de0e3bf11923ad32652e98b51368e4bc introduced some problems. At least that is the last change to the generation logic.
cc @ANich

**Comment by scholtzan** [comment]
Ok, https://github.com/mozilla/bigquery-etl/commit/c1925039de0e3bf11923ad32652e98b51368e4bc does not seem to have caused this. At least reverting it in https://github.com/mozilla/bigquery-etl/pull/2695 shows the same error

**Comment by ANich** [comment]
Looking at CI, seems a problem with an `init.sql` file. Seems like this is the relevant discussion: https://github.com/mozilla/private-bigquery-etl/pull/57#discussion_r794962650
