### ISSUE TITLE
Add active_hours_sum to telemetry.unified_metrics

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/bigquery-etl#2716]
Now that the browser KPIs are finalized for the year, I would like to add `active_hours_sum` from desktop clients_daily to telemetry.unified_metrics, so that we can use the unified table to track qualified days of use (clients with > 0 active hours and uris)

there is a wrinkle here that the metric is only available (and makes sense) on desktop, so we will have to tolerate it being NULL for all other products in the unified table. 

~once this is done, I think we can also proceed [with the backfill](https://bugzilla.mozilla.org/show_bug.cgi?id=1737674) of clients_daily~

**Comment by jklukas** [comment]
IIUC, there's no change needed to clients_daily for this. The relevant field already exists. It's rather a backfill of the `unified_metrics` table that would be needed for this and it doesn't have to be resolved before proceeding with https://bugzilla.mozilla.org/show_bug.cgi?id=1737674

**Comment by irrationalagent** [comment]
yes you are correct, I'm not sure what I was thinking there. 

the unified table has never been backfilled ever (I think data goes back to octoberish), so that would need to be done anyway. should I file a separate bug for that? 

I am hoping the unified table will support our browser KPI reporting for this year so it would be great if this could be done soon-ish :)
