### ISSUE TITLE
Update logic for parsing engine and source from search counts keys

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#2719]
See discussion in https://github.com/mozilla/bigquery-etl/pull/2718#pullrequestreview-880690948

We have been using a regex `.+[.].` which has a greedy `+` that will extract too much into the `engine` field if there's a period later on in the key. We should change that to `.+?[.].` to improve this situation.

It's particularly important now that the pipeline sometimes sends `other.scrubbed` at the end of these strings. These are currently getting incorrectly parsed.

The regex exists both in the main_summary query and the clients_daily query.

**Comment by ANich** [comment]
Closed by https://github.com/mozilla/bigquery-etl/pull/2727
