### ISSUE TITLE
Support running in alternate projects

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#277]
A request we've seen is to use bigquery-etl and it's tooling (alongside Airflow) for other projects. This issue will cover how we can tackle that.

To start, we can move all datasets to their own project's directory; e.g. `telemetry` will move to `moz-fx-data-shared-prod/telemetry`.

We will add codeowners to each project, such that the Data Engineering team doesn't need to review queries that are in other projects (unless they own them).

We will need to enable the BQ command in the GKE cluster to use alternate projects. Some options might be:
- Give GKE access to all projects
- Run the workload inside the associated project's GKE cluster, which Airflow needs access to

cc @jklukas

**Comment by jklukas** [comment]
One issue with this is that we've so far attempted to keep queries as agnostic of dataset as possible. Many of our existing queries read and write from a single dataset, so they can use simple names for all tables and we are able to use flags on `bq` to set the project and dataset in which to run them. This is useful for testing, for example.

By making the project name an explicit part of the file path, we lose some of that flexibility. For queries defined under `moz-fx-data-shared-prod`, for example, we may want to be able to run them in nonprod, too.

That said, view definitions already require fully qualified table references, so they are inherently not as portable as incremental queries. We may need to develop tooling to replace project names anyway, in which case it would probably be trivial to support applying queries to nonprod even though they're defined under the `moz-fx-data-shared-prod` directory.

**Comment by jklukas** [comment]
Thinking more on this, I'm beginning to think it makes sense to put queries underneath directories named as the project. These paths will reflect the production locations of the tables/views and then we can build our query execution tooling to allow substitution of project names, etc. to handle testing and non-prod use cases.

**Comment by trink** [comment]
Any ETA on this, it is now blocking; we have push scheduled jobs about as far as we can and are hitting limitations

**Comment by jklukas** [comment]
This has not yet been prioritized such that it has an ETA.

Do you have an estimate of how many queries would be involved? If it's a limited number, we can probably accommodate it in the existing directory structure and we can ensure we hit the correct project via configuration at the Airflow layer when we schedule the queries. We already are dealing with some amount of project skew as between the derived-datasets and shared-prod projects.

**Comment by trink** [comment]
There are about a dozen queries

**Comment by jklukas** [comment]
> There are about a dozen queries

Thinking more about this, I suppose the number of queries doesn't particularly matter as long as we document well what we're doing.

Can I assume these queries are all populating tables in one dataset? Let's assume that dataset is called `taskcluster_derived`. Then we can put the queries in `templates/taskcluster_derived` and add a README.md there that indicates these are for a different project and will be configured as such in Airflow.

We'll need to make sure Airflow has privs to read from and write to the necessary datasets. It would be ideal, actually, if we can give Airflow permission to create query jobs in the taskcluster project. If not, we'll need to make sure that the queries all use fully-qualified table references.

Does that give you enough to get started? Do you foresee any other complications with this approach?

**Comment by trink** [comment]
For now the SQL scripts were modified to not use parameters since they aren't allowed `Invalid value: configuration.query.queryParameters cannot be set for scripts;`  This buys us some time so we can avoid forcing it in now and possibly having to re-work it later.  If we get to the point where we have to use airflow before this is resolved I may take you up on the proposal above (the assumptions are correct), thanks.

**Comment by jklukas** [comment]
> For now the SQL scripts were modified to not use parameters since they aren't allowed `Invalid value: configuration.query.queryParameters cannot be set for scripts;`

So you are using multi-statement scripts (beta scripting feature of BQ) for this ETL? We have not crossed that that line yet in this repo; everything is a classic single-statement query.

**Comment by trink** [comment]
Yes, since the billing data is latent we delete and then recreate the data in the latent window each night which requires a pair of queries.
