### ISSUE TITLE
Remove probes that cause error on GLAM from ETL

### ISSUE THREAD

**Issue by edugfilho** [mozilla/bigquery-etl#2792]
Implement a quickfix to stop calculating probes that cause error on GLAM
[More context here](https://github.com/mozilla/glam/issues/1865).

**Comment by edugfilho** [comment]
I think those probes aren't being calculated anymore, as they're not present in the `payload` column of `telemetry_derived.main_v4`.

My understanding:  
[clients_daily_histogram_aggregates_v1.sql.py fetches the list of histogram probes from that `payload` column](https://github.com/mozilla/bigquery-etl/blob/5fc167f3283667cc535d0c8d49f36c0a4e7a3a85/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_v1.sql.py#L416) and takes the overlap between that and the probes preceded with `histogram/` from the result of a call to `https://probeinfo.telemetry.mozilla.org/firefox/all/main/all_probes`. Now since the names for the probes in question aren't present in `telemetry_derived.main_v4`, they're not picked up by the script. I could confirm that by running the script locally.

@alekhyamoz does that make sense? 
If so, do you know who we should talk to in order to clarify why those probes were removed and see whether they're going to be put back? Because the probe dictionary says they're not expired ([sqlite_store_open](https://probes.telemetry.mozilla.org/?search=sqlite_store&view=detail&probeId=histogram%2FSQLITE_STORE_OPEN), [sqlite_store_query](https://probes.telemetry.mozilla.org/?search=sqlite_store&view=detail&probeId=histogram%2FSQLITE_STORE_QUERY))

**Comment by alekhyamoz** [comment]
@edugfilho  these are keyed histogram, so may be we need to look at `payload.keyed_histograms.sqlite_store_open`

**Comment by edugfilho** [comment]
@alekhyamoz you're right! Thank you for the correction.
The script does produces the probes for keyed histograms. I'll move on with the MR
