### ISSUE TITLE
Create public tables in the correct project

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#295]
This task follows-up on [Bug 1573822](https://bugzilla.mozilla.org/show_bug.cgi?id=1573822) and #294. Once we're able to label public BQ datasets, we will need to write those query results to the public BQ project (instead of the default project).

Once the data is there, we will also write an internal view on that data in the default project.

This will take the format of:
- `bin/entrypoint` reading the `metadata.yaml`, and determining if this is a bq-public query
- If it is not, continue as before
- if it is, write to the public project
- write a view to the default project on that public table

Depending on the outcome in bug 1573822, we may also need to create the dataset in the public project (if it doesn't exist). We should coordinate with ops in that bug on how we want to tackle that.

**Comment by scholtzan** [comment]
Done in https://github.com/mozilla/bigquery-etl/pull/771
