### ISSUE TITLE
Dump public JSON data to the correct bucket

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#296]
This follows-up on #294. The bigquery-etl runner will need to again read the `metadata.yaml` and determine if a query is a public-json query; if so, we will need to write it to the correct place. That location is being determined in [Bug 1573826](https://bugzilla.mozilla.org/show_bug.cgi?id=1573826) That will entail the following:

0. Create the table, as done previously (also includes the public-BQ tables)
1. Parse `metadata.yaml` and determine if this is a public-json table
2. If so, use `bq extract` to write the data as ndjson to GCS
3.  Once the data is there, we need to change from ndjson to a single JSON array. This could possibly be done with a cloud function(?) or locally
4. Write the file out to `gcs://$bucket/api/v1/tables
    /$dataset/$tablename/v1/files/$date/$filename` for an incremental table, or `gcs://$bucket/api/v1/tables
    /$dataset/$tablename/v1/files/$filename` for a non-incremental table
5. Update `gcs://$bucket/api/v1/tables
    /$dataset/$tablename/v1/last_updated`

**Comment by scholtzan** [comment]
Support for publishing public data has been implemented
