### ISSUE TITLE
Add non-normalized aggregations to Glam ETL

### ISSUE THREAD

**Issue by edugfilho** [mozilla/bigquery-etl#3139]
Currently Glam ETL only builds normalized aggregations. However non-normalized aggregations are also interesting to Glam users, who are now resorting to TMO for that.

* This issue is blocked by #3091

**Comment by edugfilho** [comment]
Working on this. Steps are:

- [ ] Backfill aggregates.tmo data into BQ
- [ ] Implement non-normalized aggregations on GLAM ETL
- [ ] Update GLAM models to accomodate for non-normalized aggregations
- [ ] Deploy to Prod

**Comment by ANich** [comment]
@edugfilho this is complete now right?

**Comment by edugfilho** [comment]
Thanks, you're right! I forgot about updating this. Done
