### ISSUE TITLE
Should all SQL generators skip overwriting existing files?

### ISSUE THREAD

**Issue by sean-rose** [mozilla/bigquery-etl#3182]
Originally only [`stable_views` did](https://github.com/mozilla/bigquery-etl/blob/81fbdf6c015511307f27e14b7d5b08930cdcc7a7/sql_generators/stable_views/__init__.py#L7-L9), and now [`glean_usage` does](https://github.com/mozilla/bigquery-etl/pull/3149).  Should we have all SQL generators do the same?

The main benefit is being able to manually override generated files as needed.

Some potential drawbacks are such manual overrides being overused, and checked-in files accidentally blocking SQL generation (though the status quo has the reciprocal issue of SQL generation accidentally overriding checked-in files).

**Comment by ANich** [comment]
Agreed on the drawbacks. It sounds like an issue differentiating between "I checked in this file to replace what would have been generated" and "I checked this in by accident" or "this file is already checked in but I forgot to update it after updating the generator". We only have a few checked in files now so we could delete the ones we don't want to overwrite and hope they don't get checked in again but that isn't perfect.  

What do you think about specifying explicitly (in some generator config maybe) what file paths should be generated and/or ignored by a particular SQL generator?

**Comment by fbertsch** [comment]
+1 to this idea, that would be my expectation when putting in PRs, and fits in with our general mantra: Prefer explicit over implicit.

Dealing with the drawbacks could be a challenge, but perhaps a good path could be visibility into what the `generated-sql` branch will look like after your change is merged (as a comment on a PR) could be a path.

**Comment by sean-rose** [comment]
Copying over some comments from a [Slack thread](https://mozilla.slack.com/archives/C01E8GDG80N/p1661471288408739):
> @akkomar 
> I don't have an opinion about this apart from:
> - +1 for thinking about standardising this
> - https://github.com/mozilla/bigquery-etl/tree/main/sql_generators#readme should probably be updated with some info on the current approach
> - only somewhat related since you're asking about views and this is a query: https://github.com/mozilla/bigquery-etl/blob/main/sql_generators/search/__init__.py#L66 seems to be working in a different way than other scripts by not writing the query file and relying on the checked-in version (cc @lucia-vargas-a, @ANich)

> @lucia-vargas-a 
> To ellaborate a bit on Arkadius last comment, with the sql generators I used the documentation on the [header of the script](https://github.com/mozilla/bigquery-etl/blob/81fbdf6c015511307f27e14b7d5b08930cdcc7a7/sql_generators/search/__init__.py#L7) to actually create the query file, because the generate() function only prints to the output, but the output_directory parameter is not used. So what is still unclear is, if we delete the query files that use this function, how would the CI create them,

> @ANich 
> > not writing the query file and relying on the checked-in version
> 
> Okay wow TIL, I didn't read that far into the file.. That means that file will need more changes before removing the checked-in file then.

**Comment by sean-rose** [comment]
The `glean_usage` SQL generator is now getting a config for which files to skip overwriting (#4069), and presumably the same will be done for `stable_views` and any other applicable SQL generators, so I'm closing this issue.
