### ISSUE TITLE
Deploy assert UDFs

### ISSUE THREAD

**Issue by scholtzan** [mozilla/bigquery-etl#3221]
We use some custom `assert` UDFs to write tests for UDFs. [These UDFs]([https://github.com/mozilla/bigquery-etl/blob/main/tests/assert](https://github.com/mozilla/bigquery-etl/blob/main/tests/assert/equals/udf.sql)) have not been deployed to mozfun, but it might be useful to do so when testing UDFs in the console or in Redash.

**Comment by ANich** [comment]
Might be an opportunity to take a look at https://github.com/mozilla/bigquery-etl/issues/2472 as well

**Comment by ANich** [comment]
This was done in https://github.com/mozilla/bigquery-etl/pull/4367
