### ISSUE TITLE
Add moz-fx-data-backfill-* to allowed projects

### ISSUE THREAD

**Issue by whd** [mozilla/bigquery-etl#3255]
From https://github.com/mozilla/bigquery-backfill/pull/20/files, this was one of the gotchas for running copy-deduplicate

**Comment by scholtzan** [comment]
Running `./bqetl copy_deduplicate --project-id moz-fx-data-backfill-1` return "Invalid project" since the backfill projects are not part of this [list of allowed projects](https://github.com/mozilla/bigquery-etl/blob/9d650106d6ff8bef19e22210c912c8df1ae4ee4a/bigquery_etl/cli/utils.py#L48-L57)
