### ISSUE TITLE
Backfill Monthly partitioned queries fail due to incorrect partition date

### ISSUE THREAD

**Issue by quiiver** [mozilla/bigquery-etl#3303]
I recently created a table that is monthly partitioned. When running `bqetl query backfill domain_metadata_derived.top_domains_v1` it generates the following value for a destination date: `--destination_table=top_domains_v1$20221023` 

However, according to the docs[1] the partition value for monthly partitions should just be '%Y%m' with no day value.

[1] https://cloud.google.com/bigquery/docs/partitioned-tables#date_timestamp_partitioned_tables

**Comment by scholtzan** [comment]
We'll have to pull in the metadata when backfilling to determine the partitioning: https://github.com/mozilla/bigquery-etl/blob/e98684cb0e0fd0deaf1a622c920be3f90be23e03/bigquery_etl/cli/query.py#L465
