### ISSUE TITLE
Parser to extract Windows OS name, version, and build from an OS version string

### ISSUE THREAD

**Issue by jcchuang** [mozilla/bigquery-etl#3397]
# Need for a new SQL user-defined function (UDF)
Our ETL tools currently don't have an efficient way to extract the OS name, version name, version number, and build number from a Microsoft Windows OS version string.

The closest existing UDF `mozfun.norm.windows_version_info` can produce a _standardized_ OS name when given an OS name, OS version number, and OS build number. However, all these values can actually be extracted directly from an OS version string without additional knowledge. This UDF requires additional input about OS names and build numbers in order to run. This UDF only normalizes the OS name and does not extract the other fields.

There are no efficient built-in SQL operations, either. The Windows OS version string has evolved over the years -- from a 3-number string (`x.y.z`) to a 4-number string (`w.x.y.z`), from embedding the version number in the first two digits (`x.y` of `x.y.z`) to embedding the version number in the third digit (`y` of `w.x.y.z`), among other idiosyncratic characteristics. Therefore, parsing cannot be done via simple array manipulations, string operations, or type conversions.

# Proposed UDF
The first version of the proposed UDF is designed to extract the OS name, version name, version number, and build number from the Microsoft Windows OS version string collected in field `os_version` of table `mozdata.default_browser_agent.default_browser`.

The proposed UDF contains sufficient contextual information about Microsoft Windows systems running in the past 26 months (from Windows Vista to Windows 11), and is expected to parse approximately 99.89% of the OS version string values observed in the `os_version` field as of November 2022.

**Comment by wwyc** [comment]
@jcchuang it looks like the new udf has been merged.  Should this issue be closed?

**Comment by jcchuang** [comment]
Resolved in https://github.com/mozilla/bigquery-etl/pull/3398
