### ISSUE TITLE
Start importing amplitude events from FxA oauth server into BQ datasets

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/bigquery-etl#348]
We need to start counting FxA amplitude events from the oauth server logs, e.g. `moz-fx-fxa-prod-0712.fxa_prod_logs.docker_fxa_oauth_YYYYMMDD`

We currently only import events from the auth and content servers into bigquery. 

I believe this to be the cause of at least part, perhaps all of the discrepancy between the GUD dashboard's account of FxA MAU and amplitude https://analytics.amplitude.com/mozilla-corp/chart/sxp5s3v.

We will also need this for skyline reporting purposes. 

IIUC it should be possible to write a similar pipeline to the current jobs that slurp from the auth/content servers. Then we would also need to update the derived datasets so that they start counting these events.

**Comment by jklukas** [comment]
Sounds reasonable. Should be fairly straightforward.

**Comment by jklukas** [comment]
I'm not seeing `jsonPayload.type = 'amplitudeEvent'` like in other tables, but I do see `*.amplitudeEvent`. Should I accept any event where the type ends with amplitudeEvent?

**Comment by irrationalagent** [comment]
@jklukas I think this would be ok but checking with @philbooth to confirm?

**Comment by philbooth** [comment]
> I'm not seeing `jsonPayload.type = 'amplitudeEvent'` like in other tables, but I do see `*.amplitudeEvent`. Should I accept any event where the type ends with amplitudeEvent?

Just looked at the code in the oauth server, so are you seeing e.g. `routes.verify.amplitudeEvent`? It seems unfortunate we did it like that, but yeah, I don't see anything else logging with that string so you should be fine to match it like that.

**Comment by jklukas** [comment]
> routes.verify.amplitudeEvent

Yes, that's one of the variants. There are a few. I'll proceed with `jsonPayload.type LIKE '%.amplitudeEvent'` in the query

**Comment by jklukas** [comment]
It looks like `jsonPayload.fields.op` equals "amplitudeEvent" for all cases where the jsonPayload.type ends in amplitudeEvent. Would that be a more reasonable thing to filter on?

**Comment by philbooth** [comment]
Yep, definitely, do that!

**Comment by irrationalagent** [comment]
> It's possible to recalculate dependent tables so that we get a full recalculation of MAU with `oauth` included. Is that desirable?

I think it is. We are already counting these events in amplitude toward our tracking of MAU so I don't see an obvious reason why wouldn't try to bring these tables into alignment with that.

**Comment by jklukas** [comment]
I've completed the backfill. GUD currently relies on a nightly query that runs at 8:45 AM Pacific to do a full refresh of its data. Once that completes today, GUD should show the backfilled fxa numbers. The query can take over an hour to run, so you might need to wait a little bit before validating.

**Comment by irrationalagent** [comment]
(using this issue for efficiency)

@jklukas so the filter we talked about adding to the job that imports the oauth amplitude events would filter out (exclude) all amplitude events where the `oauth_client_id` field matches one of the following values

`3332a18d142636cb`
`5882386c6d801776`
`1b1a3e44c54fbb58`

thanks Jeff :)
