### ISSUE TITLE
Workflow docs are wrong

### ISSUE THREAD

**Issue by rebecca-burwei** [mozilla/bigquery-etl#3503]
Docs: https://mozilla.github.io/bigquery-etl/cookbooks/common_workflows/#example-add-a-new-field-to-clients_daily

Step 4 says to run `./bqetl query schema update`, but I get:
```
% ./bqetl query schema update telemetry_derived.clients_daily_v6 --update_downstream
Usage: bqetl query [OPTIONS] COMMAND [ARGS]...
Try 'bqetl query --help' for help.

Error: No such command 'schema'.
```

**Comment by wwyc** [comment]
@rebecca-burwei are you still seeing this error?
