### ISSUE TITLE
Reprocess stable table days missing sample_id via query

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#355]
We have 6 days of data for which we were not adding sample_id, and we need to reprocess somehow to add that back in.

We have a working and reasonably efficient implementation of sample_id as a UDF in https://github.com/mozilla/bigquery-etl/pull/353 and we have the existing copy_deduplicate task that can iterate through all stable tables to run a query to populate them.

I propose that we create a variant of the copy_deduplicate script that reads from the stable table rather than the live table and just replaces the `sample_id` field in the query rather than deduplicating.

I ran a small test of this method and we were able to process a day of main ping in approximately the same time as the existing copy_deduplicate task (~21 minutes), suggesting that the bottleneck for both these jobs is simply the volume of data to be written rather than any data processing.

The cost for this will be identical to the cost for running the existing daily copy_deduplicate queries for the affected days.

cc @whd @relud

**Comment by jklukas** [comment]
I've finished reprocessing for all tables besides main ping for 2019-09-10 through 2019-09-15. Main ping is now processing.

Tomorrow, I'll need to kick off jobs for 2019-09-16 since they're also going to get populated with partially records that have no sample_id.

**Comment by jklukas** [comment]
Everything other than main ping is fixed now through 2019-09-16.

Main ping is proving to be a pain, though. Queries have taken longer that the expected ~20 minutes and have failed with OOM errors. Could be that most of these attempts were during heavy load from users or Airflow jobs, so it may have gotten fewer slots than my initial test. I am trying some variations.

**Comment by jklukas** [comment]
I have not been able to complete reprocessing of any day of main ping. I continue to hit memory errors. I believe this is the same underlying problem that causes the main ping copy_deduplicate job to fail sometimes. I have a [case open with Google](https://enterprise.google.com/supportcenter/managecases#Case/001000000040sBR/U-20528460) about it and I'm adding details about the current problem in that case as well.

At this point, we either wait for more advice from Google or I can start investigating options for extracting data to an external system for calculation and reloading. One option is trying to run a batch Dataflow job.

**Comment by relud** [comment]
what about reprocessing one hour at a time, since we are clustered by timestamp?

**Comment by jklukas** [comment]
> since we are clustered by timestamp

That's maybe an option, but I was hoping to read from stable tables which are clustered by sample_id (and all values are null, so not really clustered at all). If we read from live tables, we have to deduplicate which would require us to materialize the table of duplicated IDs in order to run per-hour queries.

**Comment by relud** [comment]
> I was hoping to read from stable tables which are clustered by sample_id

what about selecting the impacted days from stable into a timestamp clustered table, then querying from that into hourly tables with the stable clustering, then copy-appending the hours together, then copy-overwrite back into stable?

**Comment by jklukas** [comment]
> selecting the impacted days from stable into a timestamp clustered table

This step I would expect would have the same performance problems as trying to write into a sample_id-clustered table.

**Comment by relud** [comment]
> > selecting the impacted days from stable into a timestamp clustered table
> 
> This step I would expect would have the same performance problems as trying to write into a sample_id-clustered table.

To be clear, this isn't the step where we add sample_id, this step is only doing a `SELECT *`, and I would really expect `SELECT *` to be able to handle a full day of main pings.

> then querying from that into hourly tables with the stable clustering

this is the step where we add sample_id, because this is where we would be reprocessing one hour at a time.

**Comment by jklukas** [comment]
> I would really expect SELECT * to be able to handle a full day of main pings

You really would, wouldn't you ;)

I'm fairly certain the underlying problem here is the sorting step where 8 TB of data has to get sorted correctly to fit the clustering specification. We tend to not get enough slots for it to handle the necessary sorting.

**Comment by relud** [comment]
> I'm fairly certain the underlying problem here is the sorting step where 8 TB of data has to get sorted correctly to fit the clustering specification

yeah, confirmed this by trying it. this approach won't work

> If we read from live tables, we have to deduplicate which would require us to materialize the table of duplicated IDs in order to run per-hour queries.

okay, new idea: what if we use live tables, add sample_id hourly, combine hours with copy-append, and then re-run deduplication over the combined day (which should work because deduplication worked before, even if it took retries)?

**Comment by jklukas** [comment]
> okay, new idea: what if we use live tables, add sample_id hourly, combine hours with copy-append, and then re-run deduplication over the combined day (which should work because deduplication worked before, even if it took retries)

The final deduplication step would still be writing the entire day at once, which I expect would trigger this same problem of having to sort 8 TB of data before writing. I think copy_deduplicate on main is only succeeding because it's running at an exceptionally unloaded part of the day.

**Comment by relud** [comment]
I extracted the necessary days from stable to avro no gcs, and then loaded that as clustered by submission_timestamp in a separate project, and now i'm running queries that add sample_id over one hour (rather than one day), and then combining hourly tables into full days, and after we verify that it worked we can copy those into place in `moz-fx-data-shared-prod:telemetry_stable.main_v4`

**Comment by relud** [comment]
main_v4 with sample_id is now available at `moz-fx-data-derived-datasets:backfill.main_v4` for the 10th through the 16th.

the 10th didn't change at all. the 11th through the 15th all have the exact same number of rows, and exactly 8 more bytes per row, which matches the billing size of an int64. the 16th shows an increase equal to 8 bytes over 80% of rows.

**Comment by jklukas** [comment]
Did your query do a coalesce to preserve existing non-null sample_ids? It looks like all the entries from 2019-09-10 have sample_id = 69. In my earlier work on this problem, I ran a few queries where I accidentally was setting `udf_js_sample_id('foo')` (which I believe ended up giving 69 as the sample_id) rather than `udf_js_sample_id(client_id)`. I thought all of those attempts had failed, but apparently one of the attempts for 2019-09-10 completed successfully.

That would explain why you didn't see any change in the 10th.

Otherwise, this looks great and I am thrilled that we have a process that works, even if it's a pain. I especially appreciate the analysis on slight increase in bytes. It's comforting to hear that all works out as we might expect and that nulls truly don't take up storage space.

**Comment by relud** [comment]
i did coalesce, will fix

**Comment by relud** [comment]
I fixed 2019-09-10 and confirmed that each sample id exists and is getting a nearly even distribution with this query
```sql
WITH
  clusters AS (
  SELECT
    DATE(submission_timestamp) AS submission_date,
    sample_id,
    COUNT(*) AS row_count
  FROM
    `moz-fx-data-derived-datasets.backfill.main_v4`
  WHERE
    DATE(submission_timestamp) BETWEEN '2019-09-10' AND '2019-09-16'
  GROUP BY
    1,
    2)
SELECT
  submission_date,
  COUNT(*) AS cluster_count,
  (MAX(row_count) - MIN(row_count))/AVG(row_count) AS deviation_percent
FROM
  clusters
GROUP BY
  submission_date
ORDER BY
  submission_date
```
which returns

| submission_date | cluster_count |  deviation_percent   |
|-----------------|---------------|----------------------|
|      2019-09-10 |           100 |  0.03508765536536311 |
|      2019-09-11 |           100 |  0.05274466234570406 |
|      2019-09-12 |           100 | 0.044740380156198724 |
|      2019-09-13 |           100 |  0.05225730055741874 |
|      2019-09-14 |           100 | 0.055302258614994416 |
|      2019-09-15 |           100 |  0.06897966628383832 |
|      2019-09-16 |           100 |  0.05240154334473516 |

**Comment by jklukas** [comment]
This looks good to me. I think we're ready to copy these back into the stable table. I have access to do so.

**Comment by jklukas** [comment]
Done. We're back in business. Thanks so much for your work here, @relud.
