### ISSUE TITLE
Flaky SQL tests for fivetran_costs_derived/monthly_connector_costs_v1/test_one_connector_mutliple_months

### ISSUE THREAD

**Issue by scholtzan** [mozilla/bigquery-etl#3550]
See https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/18680/workflows/64aadb5b-f52e-48f4-a37e-5acb2f936da0/jobs/177488 
These tests seem to be failing

**Comment by scholtzan** [comment]
cc @lelilia

**Comment by sean-rose** [comment]
Fixed by #3547.
