### ISSUE TITLE
Investigate hash functions for id_bucket

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#36]
We are currently using the following calculation for assigning records and `id_bucket` which enables confidence interval calculations:

    MOD(ABS(FARM_FINGERPRINT(user_id)), 20) AS id_bucket

That is the simplest and likely most computationally efficient solution using built-in BigQuery functions. But we have not yet rigorously evaluated it for potential sources of bias:

- Fingerprint64 does not have as robust an avalanche property as cryptographic functions such as MD5 (see #33 for an MD5-based implementation)
- There may be some bias introduced by ABS

For further discussion, see https://github.com/mozilla/bigquery-etl/pull/27, https://github.com/mozilla/bigquery-etl/pull/32/files#r268184403, and #33.

**Comment by ANich** [comment]
This is mainly used in GUD datasets, GUD has been deprecated for a little while (ref?), but the tables haven't been. I guess whether this is relevant depends on whether those tables will be deprecated. cc @gkabbz

**Comment by scholtzan** [comment]
I think we can close this. Doesn't look like bias has been a concern
