### ISSUE TITLE
deploy-changes-to-stage CI step cannot handle materialized views

### ISSUE THREAD

**Issue by scholtzan** [mozilla/bigquery-etl#3665]
If any files that reference materialized views get changed, then the `deploy-changes-to-stage` CI step currently fails as it cannot deploy the view as a table, or at all. An example of where this happened: https://github.com/mozilla/bigquery-etl/pull/3623

https://circleci.com/gh/mozilla/bigquery-etl/189313

**Comment by BenWu** [comment]
Should be fixed by https://github.com/mozilla/bigquery-etl/pull/6421
