### ISSUE TITLE
More reliable copy_deduplicate for main_v4

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#367]
For the first time today, the copy_deduplicate job for main_v4 failed all 3 of its attempts. We also had significant trouble being able to copy full days of main_v4 in https://github.com/mozilla/bigquery-etl/issues/355.

We have a [case open with Google](https://enterprise.google.com/supportcenter/managecases#Case/001000000040sBR/U-20528460) to discuss the issue, which may give us some more advice on how to proceed. So far, their primary suggestion has been to run this query in a project with flat-rate billing. That _may_ give us more reliable access to large numbers of concurrent slots.

We could also break out the logic into multiple queries, as @relud has suggested. We'd run one query to materialize a table of duplicated doc IDs, then we run multiple queries for various time chunks of the live table (perhaps 24 queries that each copy 1 hour of data).

**Comment by jklukas** [comment]
Or maybe we should try using the existing query to write to a temporary unclustered table, then issuing a Copy job to load into the stable table.

**Comment by relud** [comment]
> Or maybe we should try using the existing query to write to a temporary unclustered table, then issuing a Copy job to load into the stable table.

as far as i am aware columns, clustering, and partitioning all have to match exactly for copy operations

**Comment by relud** [comment]
> > Or maybe we should try using the existing query to write to a temporary unclustered table, then issuing a Copy job to load into the stable table.
> 
> as far as i am aware columns, clustering, and partitioning all have to match exactly for copy operations

unless by copy you meant doing an extract+load, which would just need a dedicated project or quota increase to avoid using up all 10TiB/day of our extract quota.

**Comment by jklukas** [comment]
> unless by copy you meant doing an extract+load, which would just need a dedicated project or quota increase to avoid using up all 10TiB/day of our extract quota.

Yes, that's what I mean. Google bumped this quota up to 100 TiB/day (I believe permanently) for derived-datasets, so this may still be feasible without completely consuming our quota for exports.

I am testing this process now. Extracting to Avro on GCS took 21 minutes for the 2019-09-10 partition. I am now loading into a test clustered table.

**Comment by jklukas** [comment]
The load job into a clustered table hit the same memory problem:

```
BigQuery error in load operation: Error processing job 'moz-fx-data-shared-prod:bqjob_r6028f1017c031702_0000016d4f9cef8b_1':
Resources exceeded during query execution: The query could not be executed in the allotted memory. Peak usage: 113% of limit.
Top memory consumer(s):
other/unattributed: 100%
```

I will update the Google case with the above.

So it looks like we need to consider splitting up the queries to smaller time ranges, and accept the fact that clustering won't be quite ideal, but likely not noticeable for the size of the data.
