### ISSUE TITLE
Drop generated_time columns

### ISSUE THREAD

**Issue by relud** [mozilla/bigquery-etl#38]
it is a duplicate of existing bigquery table metadata (lastModifiedTime for each table/partition), so it's only useful if we aren't setting `WRITE_TRUNCATE`.

example query showing that we can see last modified time per-partition:
```bash
seq 20190323 20190324 |
    xargs -i~ bq show moz-fx-data-derived-datasets:telemetry.clients_daily_v6'$'~ |
    jq '.lastModifiedTime|fromjson|./1000' |
    TZ=UTC xargs -i~ date -d@~ +'%F %T %Z'
```
 output
```
2019-03-24 18:38:25 UTC
2019-03-25 18:30:36 UTC
```
and for the whole table:
```bash
bq show moz-fx-data-derived-datasets:telemetry.clients_daily_v6 |
    jq '.lastModifiedTime|fromjson|./1000' |
    TZ=UTC xargs -i~ date -d@~ +'%F %T %Z'
```
output
```
2019-03-25 18:30:36 UTC
```

**Comment by jklukas** [comment]
This sounds reasonable to me. I do have a slight worry that folks will be confused by the existence of the generated time columns. Seems like a detail of the pipeline that would mostly be of interest for data engineers to debug things. If our team knows about querying lastModifiedTime, we get the benefit of the timestamp without presenting it to consumers of the data.

**Comment by relud** [comment]
@mreid-moz is this okay with you, since you requested this column originally?

**Comment by relud** [comment]
need to check this for being present in the sql available metadata for a table

**Comment by relud** [comment]
@mreid-moz this information is not available in sql

**Comment by relud** [comment]
assigning @mreid-moz to make a decision on this

**Comment by relud** [comment]
i will add: I don't think it's cost effective to use this column from sql to filter which partitions need updating. if we could see it in the metadata tables that might be a different story.

**Comment by mreid-moz** [comment]
Sorry for the slow reply, I think this is fine. The case where I thought it would be useful from SQL is for relatively small aggregate tables such as MAU28 -- if the underlying data was backfilled, you could "cascade" the backfill to aggregate data generated during the affected period. 

It seems like we could do the same using the metadata as described here, without the additional (and I agree, potentially confusing) implementation detail leaking through to the "public" interface for the tables.
