### ISSUE TITLE
CI fails not finding stage files due to randomly generated dataset name

### ISSUE THREAD

**Issue by lucia-vargas-a** [mozilla/bigquery-etl#3889]
CI is randomly failing during [UDF deploy ](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/21479/workflows/0a3f8f02-3b69-4dd5-b70e-7a4772110877/jobs/212496) and  [metadata validation ](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/21480/workflows/86b9d70e-1ee3-423c-9c88-836bf14dcf6c/jobs/212536) (mostly change control validation).

The problem is that the processes look for the dataset names as set in the code, but the code can be deployed to stage using random dataset's names and therefore cannot be found.

**Comment by lucia-vargas-a** [comment]
Some options:
- Retrieve the temp dataset name and use it for metadata validation.
- Use regex to accept dataset name with random chars or empty in validations.

This options wouldn't work for UDFs unless the dataset is replaced in the code, e.g. [failure due to dataset name inside UDF norm.browser_version_info](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/21479/workflows/0a3f8f02-3b69-4dd5-b70e-7a4772110877/jobs/212496?invite=true#step-109-60).

**Comment by ANich** [comment]
Tangentially related, but I'm also having a CI failure (https://github.com/mozilla/bigquery-etl/pull/3890). I'd upvote any changes to the stage deploy module that include some tests 😝

**Comment by lucia-vargas-a** [comment]
To solve the UDF error, the dependencies for UDFs must be added to the bigquery_etl/cli/stage.py. See update in [PR-3877](https://github.com/mozilla/bigquery-etl/blob/f22d78a096e55e3c6699d80cf71a3c4616d1e73c/bigquery_etl/cli/stage.py#L271-L275).
Thank you @scholtzan for your input!
