### ISSUE TITLE
publish_persistent_udfs failing: TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by whd** [mozilla/bigquery-etl#4053]
/CC @scholtzan 

Invoked like https://github.com/mozilla-services/cloudops-infra/blob/master/projects/data-shared/Jenkinsfile.bigquery#L254, not sure how that's any different from https://github.com/mozilla/telemetry-airflow/blob/main/dags/bqetl_artifact_deployment.py#L58. I re-ran https://workflow.telemetry.mozilla.org/log?dag_id=bqetl_artifact_deployment&task_id=publish_persistent_udfs&execution_date=2023-07-10T05%3A30%3A00%2B00%3A00&map_index=-1 and that failed too so this is probably a recent change.

```
+ ./script/publish_persistent_udfs --project-id moz-fx-data-shared-prod
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/bigquery_etl/routine/publish_routines.py", line 229, in <module>
    main()
  File "/app/bigquery_etl/routine/publish_routines.py", line 82, in main
    os.path.join(ConfigLoader.get("sql_dir"), project, args.dependency_dir),
  File "/usr/local/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1161)

**Comment by scholtzan** [comment]
Fixing this now

**Comment by scholtzan** [comment]
fixed via https://github.com/mozilla/bigquery-etl/pull/4051/files#r1260217406
