### ISSUE TITLE
Bug in structured_detailed_error_counts_v1

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#414]
When I tried to publish structured_detailed_error_counts_v1, I got:

> google.api_core.exceptions.BadRequest: 400 Table name "structured_hourly_errors" missing dataset while no default dataset is set in the request.

Indeed, that CTE is never defined in that query.

cc @fbertsch

**Comment by whd** [comment]
I'm also seeing this in today's prod schema deploy, which currently blocks dataflow deployment (though it probably shouldn't).
