### ISSUE TITLE
Update clients_daily_v6 to read from telemetry_stable.main_v4

### ISSUE THREAD

**Issue by relud** [mozilla/bigquery-etl#437]

**Comment by jklukas** [comment]
Are we aware of any blockers on this, or is it simply a matter of prioritizing the work of rewriting and validating the query?

**Comment by relud** [comment]
#482 implements this, but it hasn't been merged because it relies on `main_v4` fields that weren't pulled out of `additional_properties` until november, so it would complicate backfilling, such as for [Bug 1598002](https://bugzilla.mozilla.org/show_bug.cgi?id=1598002)

**Comment by jklukas** [comment]
Completed in https://github.com/mozilla/bigquery-etl/pull/1519
