### ISSUE TITLE
Consider Creating a `clients_yearly` or similar table for Firefox for iOS

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/bigquery-etl#4428]
[~accountid:712020:2b4db328-7f77-4f81-afdc-1113ae0e970c] and I were taking a look on what is needed to start developing iOS LTV models. We initially thought that we might be able to use clients_last_seen for this, but we realized that it won’t work (easily) because clients drop off the table after 28 days.

Ultimately a clients_yearly or similar type of representation would be helpful not just for LTV but for longer-term retention analyses as well.

[Some more details in this notebook](https://colab.research.google.com/drive/1T0aHrUcT-WQK8twTIjwa-e_1RYqoLZTh#scrollTo=GlDiDLInEghC)

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/DENG-1782)

**Comment by data-sync-user** [comment]
➤ Jeffrey Silverman commented:

And this is already done for Firefox on Android, right Leif Oines ? If so, could we please include a link to the code that created that yearly table?

**Comment by data-sync-user** [comment]
➤ Leif Oines commented:

Here is the link to the fenix code ( https://github.com/mozilla/bigquery-etl/tree/main/sql/moz-fx-data-shared-prod/fenix_derived/clients_yearly_v1 )

**Comment by data-sync-user** [comment]
➤ Rob Miller commented:

Ping George Kaberere for awareness

**Comment by jmsilverman** [comment]
I'm not sure the standard way to connect a PR to an issue in GitHub, but this PR (https://github.com/mozilla/bigquery-etl/pull/4454) is a superset of what this issue is requesting I believe.

**Comment by data-sync-user** [comment]
➤ Jeffrey Silverman commented:

It looks like Frank Bertsch is working on this via https://github.com/mozilla/bigquery-etl/pull/4454 ( https://github.com/mozilla/bigquery-etl/pull/4454|smart-link )
