### ISSUE TITLE
`bqetl query backfill` does not support non-partitioned tables

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#4532]
The table `fenix_derived.client_adclicks_history_v1` is not partitioned, but I would like to backfill it by-day:
```
bqetl query backfill fenix_derived.client_adclicks_history_v1 --sql_dir sql --project_id moz-fx-data-shared-prod --start_date 2020-08-01 --end_date 2023-11-07 --max_rows 4 --parallelism 1 --checks
```

However the above fails with:
```
  File "/Users/fbertsch/repos/bigquery-etl/bigquery_etl/cli/query.py", line 725, in backfill
    partitioning_type = metadata.bigquery.time_partitioning.type
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'type'
```

Looking through the code, we hardcode the partitioning spec in several places (it requires daily or monthly in both `backfill` and `_backfill_query`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1934)

**Comment by ANich** [comment]
I've been looking into this on and off as a part of the managed backfills work. There's also a couple other things that aren't by default supported:
- `date_partition_offset` (technically possible iff there's also a `date_partition_parameter`) 
- Queries with additional parameters

I'm working on a few suggestions/PRs. I'll link this issue where relevant
