### ISSUE TITLE
CI Comments should show new DAGs

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#4573]
The CI comments right now show just changes to existing DAGs. We should also show new DAGs generated by `generate-dags` (see e.g. [this PR](https://github.com/mozilla/bigquery-etl/pull/4554)).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1986)

**Comment by ANich** [comment]
Fixed in #4593
