### ISSUE TITLE
No DAU or new profiles on firefox_ios.baseline_clients_yearly 11/16-11/17

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/bigquery-etl#4594]
I am not seeing any DAU (days_since_seen = 0) or new profiles (first_seen_date = submission_date) on firefox_ios.baseline_clients_yearly for submission_dates 2023-11-16 and 2023-11-17. There ARE rows for those submission_dates, so this is an issue with either first_seen_date or days_seen_bytes on those partitions. 

[query](https://sql.telemetry.mozilla.org/queries/96089/source)

I DO see expected first_seen_dates mozdata.firefox_ios.baseline_clients_daily

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2013)

**Comment by data-sync-user** [comment]
➤ Frank Bertsch commented:

I’ve backfilled the affected data and added dependencies to keep this from happening again.

The short version - our DAG generation code didn’t recognize the clients_daily dependency in the query, so it doesn’t wait for that task to complete before running baseline_clients_yearly. Most of the time the task runs after clients_daily completes anyways, but on those two days the clients_daily job took longer than normal and wasn’t complete when clients_yearly ran. With the new dependencies and checks, this shouldn’t happen again.
