### ISSUE TITLE
Need appropriate location for DAP data storage

### ISSUE THREAD

**Issue by simon-friedberger** [mozilla/bigquery-etl#4617]
### What is the issue?

For previous experiments we stored the data retrieved from DAP via the [airflow job](https://github.com/mozilla/docker-etl/blob/main/jobs/dap-collector/dap_collector/main.py) in mozdata/analysis/sfriedberger_dap_test. We would like to move it to a more sensible location assuming ongoing usage with production data.

We also need some configuration for this airflow job which is currently [hardcoded in Python](https://github.com/mozilla/docker-etl/blob/d34c73c424d0af798dd9201b5f79425f3de4465b/jobs/dap-collector/dap_collector/main.py#L14C1-L28C2). @akkomar suggested a GC bucket, I just wanted to double check if there are other options that people might prefer in such a case.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2081)

**Comment by akkomar** [comment]
> For previous experiments we stored the data retrieved from DAP via the [airflow job](https://github.com/mozilla/docker-etl/blob/main/jobs/dap-collector/dap_collector/main.py) in mozdata/analysis/sfriedberger_dap_test. We would like to move it to a more sensible location assuming ongoing usage with production data.

We can create a dataset in `moz-fx-data-shared-prod`, for example `dap_derived`.

> We also need some configuration for this airflow job which is currently [hardcoded in Python](https://github.com/mozilla/docker-etl/blob/d34c73c424d0af798dd9201b5f79425f3de4465b/jobs/dap-collector/dap_collector/main.py#L14C1-L28C2). @akkomar suggested a GC bucket, I just wanted to double check if there are other options that people might prefer in such a case.

Added to Thu meeting agenda, we'll get back with something.

**Comment by akkomar** [comment]
> We also need some configuration for this airflow job which is currently [hardcoded in Python](https://github.com/mozilla/docker-etl/blob/d34c73c424d0af798dd9201b5f79425f3de4465b/jobs/dap-collector/dap_collector/main.py#L14C1-L28C2). @akkomar suggested a GC bucket, I just wanted to double check if there are other options that people might prefer in such a case.

@simon-friedberger it would be easiest to go with a GCS bucket that you control and give Airflow read access.

**Comment by akkomar** [comment]
Dataset was created in https://github.com/mozilla/bigquery-etl/pull/4703
GCS bucket was created in https://github.com/mozilla-it/webservices-infra/pull/1375
