### ISSUE TITLE
DAG Generation missed a `clients_daily` dependency

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#4621]
In the `bqetl_firefox_ios` dag, the `baseline_clients_yearly` query queries the `baseline_clients_daily` table. We expect that DAG generation will pick up on this dependency and add a task dependency.

However the [DAG does not have that dependency](https://github.com/mozilla/bigquery-etl/blob/6fdbe615c2f88688f2b128a400650b92a509e244/dags/bqetl_firefox_ios.py), even though the query queries `moz-fx-data-shared-prod.firefox_ios_derived.baseline_clients_daily_v1`.

Other things I tried:
- Removing the project ID reference
- Querying the table instead of the view

Neither of the above (and neither together) were able to resolve the dependency.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2091)

**Comment by scholtzan** [comment]
fixed
