### ISSUE TITLE
clients_last_seen has string sample_id in the underlying table

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#466]
This is likely something we were planning to fix when moving the table to shared-prod, but the underlying telemetry_derived.clients_last_seen_v1 table has sample_id as a string, meaning we get no benefit from clustering when it's queried through the view (which casts sample_id to int).

Does that match your understanding, @relud?

**Comment by relud** [comment]
yes. see also https://bugzilla.mozilla.org/show_bug.cgi?id=1567025

**Comment by jklukas** [comment]
This is now resolved and clients_last_seen has integer sample_id
