### ISSUE TITLE
rewrite main summary using scripting

### ISSUE THREAD

**Issue by relud** [mozilla/bigquery-etl#467]
when [BigQuery scripting](https://cloud.google.com/bigquery/docs/reference/standard-sql/scripting) becomes GA or if we decide to accept the risk of using it in beta.

this should allow us to use temporary tables to generate main summary without [script/run_multipart_query](https://github.com/mozilla/bigquery-etl/pull/258/files#diff-04a5f1f3b9457c479fe8e65e4314edd5)

**Comment by jklukas** [comment]
We will not make further investments in main_summary.
