### ISSUE TITLE
implement udf_gunzip as a stored procedure

### ISSUE THREAD

**Issue by relud** [mozilla/bigquery-etl#468]
it would require implementing gzip as sql, but if it's more performant than [udf_js/gunzip](https://github.com/mozilla/bigquery-etl/blob/master/udf_js/gunzip.sql) it might be worth it

https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_procedure

**Comment by jklukas** [comment]
> it would require implementing gzip as sql

Do you think that could be feasible?

**Comment by relud** [comment]
I think it's probably possible 😈

**Comment by relud** [comment]
stored procedures don't work they way i thought when i filed this. gunzip isn't currently possible via stored procedures.
