### ISSUE TITLE
Spurious integration task failures due to /tmp/gcp.json is not a valid json file

### ISSUE THREAD

**Issue by scholtzan** [mozilla/bigquery-etl#4856]
Integrations tests are sometimes failing with:

```
google.auth.exceptions.DefaultCredentialsError: ('File /tmp/gcp.json is not a valid json file.', JSONDecodeError('Expecting value: line 1 column 1 (char 0)'))
```

This is likely related to the general instability of the BQ client library. 

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2436)

**Comment by sean-rose** [comment]
I believe this was fixed by #4997.
