### ISSUE TITLE
Data missing from fenix.clients_yearly on 2024-01-08

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/bigquery-etl#4865]
[Query](https://sql.telemetry.mozilla.org/queries/97095/source) - I believe this means that subsequent days will also be incorrect.

I checked upstream in [`baseline_clients_daily`](https://sql.telemetry.mozilla.org/queries/97096/source) but that table seems intact on a quick glance.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2459)

**Comment by fbertsch** [comment]
This is fixed and the future dates & downstream jobs backfilled.
