### ISSUE TITLE
Add custom ping into Shredder

### ISSUE THREAD

**Issue by tomrittervg** [mozilla/bigquery-etl#5197]
The [user-characteristics ping](https://searchfox.org/mozilla-central/source/toolkit/components/resistfingerprinting/pings.yaml#8) does not include a client id, but instead [implements its own identifier](https://searchfox.org/mozilla-central/source/toolkit/components/resistfingerprinting/metrics.yaml#31-50).  This identifier is sent in the `deletion-requests` ping but - as I understand it - Shredder needs to be taught to recognize this identifier and then delete the data out of the separate ping.

This ping is not enabled on release - the only people who have enabled it are FF engineers volunteering to populate the tables with some test data.  However having this wired up via Shredder is a prerequisite to enabling on release I think.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3010)

**Comment by BenWu** [comment]
I'm looking at `metrics.uuid.characteristics_client_identifier` in the `firefox_desktop.deletion_request` table and there aren't any non-null values so it doesn't look like any deletion requests for this have been sent yet.  @tomrittervg can you confirm if this is the right field to use for deletion requests?

It might be useful to have a deletion request to make sure we get the right fields wired up.  Can you try sending one or is there a pref I can toggle to do it on my own client?

**Comment by tomrittervg** [comment]
IF you set [this pref](https://searchfox.org/mozilla-central/rev/d7c5387a43bda5163afcb9e65e17c476c6ecf625/modules/libpref/init/all.js#635) to 1 and then restart Firefox, you'll submit a ping.  IF you disable telemetry, you should send a deletion request (AIUI.)  I've just done this myself, so the deletion request should be working its way through the system, you can add yours as well.

**Comment by BenWu** [comment]
Alright I found my own deletion ping and everything looks as expected.  This should be straightforward to do so I'll try to work on it in the next week

**Comment by BenWu** [comment]
The user-characteristics ping was added to shredder in https://github.com/mozilla/bigquery-etl/pull/5341
