### ISSUE TITLE
Use submission_date field to partition clients_scalar_aggregates

### ISSUE THREAD

**Issue by emtwo** [mozilla/bigquery-etl#535]
This is a follow-up to https://github.com/mozilla/bigquery-etl/pull/533
We'd like to be able to use clustering, but there must be a partition to do so.
Currently it implements the partition using `app_version` but this is a beta feature and it doesn't seem to suit our needs.

We can create a dummy date field instead that we partition on so that we're able to use the clustering capabilities.

**Comment by emtwo** [comment]
Update: there existed a date field for partitioning histogram aggregates, but this needs to be added to scalar aggregates

**Comment by emtwo** [comment]
This is fairly important so that data is not lost when we overwrite `clients_scalar_aggregates` on each run

**Comment by Ben-Wu** [comment]
Fixed with #1216 and validated
