### ISSUE TITLE
 IFNULL in favor of COALESCE

### ISSUE THREAD

**Issue by relud** [mozilla/bigquery-etl#542]
`IFNULL` is an alias for `COALESCE` that's limited to 2 arguments.

we should consider whether to:
1. allow both, and require `IFNULL` for the 2 argument case
1. allow both and let the author choose what to use for the 2 argument case
1. only allow `COALESCE`

argument for option 1: it's short and consistent
argument for option 2: it's easy
argument for option 3: it's easy and consistent and potentially more compatible with other sql variants

**Comment by jklukas** [comment]
Do we have any method currently of enforcing any of the above rules? If not, I don't think it's reasonable to expect us to rely on code review to catch violations of (1) or (3), so I'd be fine with (2).

**Comment by relud** [comment]
we can add a simple linter that applies regexes to catch violations of 3. catching 1 requires a linter that parses expressions, so that we can tell how many arguments there are, which is much harder.

**Comment by relud** [comment]
i don't think this is worth the effort for now
