### ISSUE TITLE
Use schema.yaml for static tables instead of schema.json

### ISSUE THREAD

**Issue by scholtzan** [mozilla/bigquery-etl#5476]
Currently, static tables loaded from, for example, CSV files use a `schema.json` file for creating the BigQuery tables. Since all other queries use `schema.yaml` we should update the tooling and schema files for static tables to also be `schema.yaml`. An example for a static table is here: https://github.com/mozilla/bigquery-etl/tree/main/sql/moz-fx-data-shared-prod/static/country_names_v1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3598)

**Comment by data-sync-user** [comment]
➤ Sean Rose commented:

This was resolved by https://github.com/mozilla/bigquery-etl/pull/5491 ( https://github.com/mozilla/bigquery-etl/pull/5491|smart-link ).
