### ISSUE TITLE
[Data Checks Bug]: Apple CPUs are represented as empty string

### ISSUE THREAD

**Issue by saschanaz** [mozilla/bigquery-etl#5534]
### What is the issue?

https://data.firefox.com/dashboard/hardware shows growing empty string vendor. This is actually Apple.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3692)

**Comment by BenWu** [comment]
I was looking at doing a backfill and from what I can see, cpu name only started being reported as Apple in late 2022 (I think Firefox 108) so we're still going to have an empty string for a few months.  Still better than nothing though.  There are probably ways to clean it up but not something I'm going to look into right now
