### ISSUE TITLE
`event` column from `events_stream` inaccessible in Looker

### ISSUE THREAD

**Issue by akkomar** [mozilla/bigquery-etl#5903]
[`event` column from `events_stream` tables](https://github.com/mozilla/bigquery-etl/blob/1811b870fdb6d56f48cd7cc5866b50c8272f673d/sql_generators/glean_usage/templates/events_stream_v1.query.sql#L123) is inaccessible in Looker because in the generated LookML it is superseded by [`event_timestamp` field](https://github.com/mozilla/bigquery-etl/blob/1811b870fdb6d56f48cd7cc5866b50c8272f673d/sql_generators/glean_usage/templates/events_stream_v1.query.sql#L120) that [lookml-generator renames to `event`](https://github.com/mozilla/lookml-generator/blob/8a5bee98eeeef7ded36f739cb4b06677247789e7/generator/views/lookml_utils.py#L62-L67).

@quiiver @badboy @scholtzan by any chance were you aware of that?
Exposing this column in Looker would make events_stream explores more useful. I guess the easiest fix would be to add an alias field in the view (e.g. `full_event_name`).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4290)

**Comment by badboy** [comment]
I did not know that, no. I also don't know enough about Looker to say what the right way to fix that is.

**Comment by akkomar** [comment]
I looked into this more and I think it might be best to handle this in lookml-generator by aliasing `event` column to `full_event_name`. Filed https://github.com/mozilla/lookml-generator/pull/1007
