### ISSUE TITLE
CI may be running stale tests in some cases

### ISSUE THREAD

**Issue by BenWu** [mozilla/bigquery-etl#5974]
https://github.com/mozilla/bigquery-etl/pull/5957 introduced a udf with some unit tests that were incorrect and failed but the `test-routines` CI task didn't seem to run them in the PR or after merging to main.  `test-routines` succeeded on this commit https://github.com/mozilla/bigquery-etl/commit/808207024ff0296f4c7b7897c5a1de2db6f9c67e but failed on the next https://github.com/mozilla/bigquery-etl/commit/2b425fc5f75e909f6bc1124dca182a1b6eb01300.  The test count also goes up in the second commit.

This can caused failed tests to be committed to main which will then block future merges since `test-routines` is a required check

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4396)

**Comment by scholtzan** [comment]
The configured testpaths seem to exclude anything that is being deployed to stage (`bigquery-etl-integration-test`):

```
$> PATH="venv/bin:$PATH" script/entrypoint -m routine -n 8

DEBUG: SETTING UP CREDS BLOCK HIT
DEBUG: Wrote 2327 bytes to '/tmp/gcp.json'.
============================= test session starts ==============================
platform linux -- Python 3.11.9, pytest-7.4.3, pluggy-1.0.0
rootdir: /root/project
configfile: pytest.ini
testpaths: bigquery_etl, tests, sql/moz-fx-data-shared-prod/udf, sql/moz-fx-data-shared-prod/udf_js, sql/mozfun, script
```

Adding the staging project results in a bunch of `ValueError`s as the testing logic doesn't seem to be handling full-qualified identifiers in tests correctly at the moment.
