### ISSUE TITLE
Update experiments view

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#600]
It looks like the underlying table transitioned to shared-prod, but the view wasn’t updated to do a union. That should be fixed.

**Comment by relud** [comment]
this should have been done in #566, so maybe views aren't being automatically deployed?

**Comment by relud** [comment]
possibly also impacting the events view, from what I'm reading in slack

**Comment by jklukas** [comment]
It looks like the `experiments` view is referencing `derived-datasets`, where it should reference shared-prod, so that _could_ be related to this issue.

**Comment by relud** [comment]
even if it were, experiments_v1 should be automatically deployed to both locations, right?

**Comment by relud** [comment]
I've manually deployed `experiments_v1` in derived-datasets

**Comment by relud** [comment]
also, `experiments_v1` wasn't up to date in `shared-prod`

**Comment by jklukas** [comment]
It looks like `experiments_v1` gets ignored by the publish_views script because of the comment at the top of the file. The script incorrectly sees the comment as a token and we don't recognize it as a valid view, so it gets silently skipped. We need an update to the script to avoid this.
