### ISSUE TITLE
Add `subscribed` field to fxa_users_daily

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#648]
@jmccrosky is working on a forecast that looks at newsletter subscription events. The query currently hits raw fxa auth event data and scans 1.6 TB:

```
SELECT
            DATE(timestamp) as date,
            COUNT(DISTINCT jsonPayload.fields.user_id) as value,
        FROM
            `moz-fx-data-derived-datasets.telemetry.fxa_auth_events_v1`
        CROSS JOIN
            UNNEST(SPLIT(SUBSTR(JSON_EXTRACT(jsonPayload.fields.user_properties, "$.newsletters"), 2, LENGTH(JSON_EXTRACT(jsonPayload.fields.user_properties, "$.newsletters")) - 2))) subscrib
        WHERE
            jsonPayload.fields.event_type in ('fxa_reg - email_confirmed','fxa_reg - complete')
            AND jsonPayload.fields.country IN ("United States", "Canada", "Germany", "France", "United Kingdom")
            AND subscrib != ""
            AND DATE(timestamp) > "2019-06-03"
        GROUP BY 1
        ORDER BY 1
```

I'd like to add a `subscribed` field to `fxa_users_daily` instead to codify this. `subscribed` would be set if the user subscribed to at least one newsletter on the given day. We'd determine that based on the user_properties and event_type conditions above.

@irrationalagent Does that sound reasonable to you? Any additional thoughts on the logic above?

**Comment by irrationalagent** [comment]
Seems like a reasonable thing to do. Eventually, I'd like to pull out those user properties into a more usable table (e.g. one row per user_id, most recent value of user properties in columns), but for now I think just adding the subscribed field to users_daily makes sense. Maybe also to users_services_daily, in case we easily want to see which services are leading to proportionally more/less subscriptions?

Also, do we want to durably set `subscribed` to `true` or `false` after we see an event where the user property is set (e.g. if someone subscribes, set the value to `true` until we see another event where it is explicitly set to `false`), or do we only set the property to a non-null value on the days it is set? We could also have a field for both e.g. `currently_subscribed` or `subscribed_on_day`. Depends on what Jesse would find most useful.

**Comment by jmccrosky** [comment]
I'm actually not familiar with this data.  My only context here is that
Daniel asked for a forecast, I asked about how to get the data needed, and
Leif gave me a query ;)

I'm very happy to defer to your expertise here Leif.  I'm guessing that
this query is finding accounts that were *ever* subscribed?  Can you
confirm?  If it's not absolutely clear what we want, I can go back to
Daniel for clarification.

**Comment by irrationalagent** [comment]
So I guess if we care about the number of registration events w/ opt-in then we would want to have just a `susbcribed_on_day` field that is true iff the user signed up for the newsletter on that day, false if they did not opt in, and null otherwise.

However if we need to ever e.g. calculate MAU among users who have already opted into the newsletters, then we also need `currently_subscribed` which will remain true or false until they opt in or out. So, maybe we need both.

**Comment by kik-kik** [comment]
This is quite an old issue, I'm not sure if this is really relevant anymore @akkomar @sean-rose  do you think we can just close this?

**Comment by akkomar** [comment]
> This is quite an old issue, I'm not sure if this is really relevant anymore @akkomar @sean-rose do you think we can just close this?

Fine by me, but I'm not familiar with this use case.

**Comment by sean-rose** [comment]
I'd defer to @irrationalagent on whether this is still something we want to do.

If it turns out we do still want to do this then I'd recommend tweaking the naming of the column(s) to include the term `newsletter`, as we now have paid subscription products and just saying `subscribed` would be ambiguous.

**Comment by kik-kik** [comment]
@irrationalagent Did you have a chance to look at this?

**Comment by irrationalagent** [comment]
OK sorry - this does look old and close-able.
