### ISSUE TITLE
CI failing on activity_stream/tile_id_types/view.sql

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/bigquery-etl#653]
I had an unrelated PR just fail the dry-run test with:
`Access Denied: Dataset pocket-tiles:pocket_tiles_data: User does not have bigquery.datasets.update permission for dataset pocket-tiles:pocket_tiles_data.` [1]

Looks like the corresponding file was merged in 3 hours ago and passed dry-run. Did something change permissions-wise in the meantime?

cc @acmiyaguchi @jasonthomas 

[1] https://circleci.com/gh/mozilla/bigquery-etl/8226

**Comment by acmiyaguchi** [comment]
From what I can tell, I don't have `bigquery.jobs.list` permissions on the `pocket-tiles` project, so it seems reasonable that the dry-run would fail. I don't know how the test passed in #650 if it actually applied the views within the test project.

**Comment by jklukas** [comment]
I'm not sure how CI succeeded on the original PR, but this is an authorized view and for now I think it makes sense to basically keep it out of the automated machinery entirely. I will make a PR to that effect so that we don't attempt to publish this view with schema deploys.

**Comment by jasonthomas** [comment]
The circleci and dry run service accounts have data viewer access to the dataset in `pocket-tiles` project. I had added those permissions after tests in #650 failed. 

I am not sure why bigquery.datasets.update permissions is required here but it might be related to authorized views. It could be that we just need to change it to `CREATE VIEW IF NOT EXISTS` instead of `CREATE OR REPLACE VIEW`.

**Comment by jklukas** [comment]
> It could be that we just need to change it to `CREATE VIEW IF NOT EXISTS` instead of `CREATE OR REPLACE VIEW`.

It looks like it still generates an error if you try to run `CREATE VIEW IF NOT EXISTS`:

> Access Denied: Table pocket-tiles:pocket_tiles_data.tile_id_types: User does not have permission to query table pocket-tiles:pocket_tiles_data.tile_id_types.

I'm adding a list of authorized views to skip in the view publishing script: #655
