### ISSUE TITLE
Document views under monitoring namespace

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/bigquery-etl#665]
There are several different monitoring views under `templates/monitoring` that are being used at the moment. We should document the views and point to the dashboards that they are powering, possibly as a README or a document string at the top of the sql.

**Comment by ANich** [comment]
cc @fbertsch Are these views/dashboards still a thing?

**Comment by scholtzan** [comment]
Pretty sure these views are now in the `monitoring/` folder
