### ISSUE TITLE
`monitoring.telemetry_missing_columns_v2` was not automatically deployed 

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/bigquery-etl#671]
#644 was merged in 2020-01-09, but as of 2020-01-13, is not available via the shared-prod project. Auto-deployment of views may not be occurring as expected.

https://sql.telemetry.mozilla.org/queries/67537/source

```
Error running query: { "error": { "code": 404, "message": "Not found: Table moz-fx-data-shared-prod:monitoring.telemetry_missing_columns_v2 was not found in location US", "errors": [ { "message": "Not found: Table moz-fx-data-shared-prod:monitoring.telemetry_missing_columns_v2 was not found in location US", "domain": "global", "reason": "notFound" } ], "status": "NOT_FOUND" } }
```

**Comment by whd** [comment]
As mentioned in the meeting just now, automatic production updates were paused last week while observing the pipeline for https://bugzilla.mozilla.org/show_bug.cgi?id=1583649. Updates should start rolling out automatically again today (tomorrow UTC).

**Comment by acmiyaguchi** [comment]
This view is now available.
