### ISSUE TITLE
Table descriptions as metadata in BigQuery

### ISSUE THREAD

**Issue by scholtzan** [mozilla/bigquery-etl#680]
Related to [bugzilla#1603536](https://bugzilla.mozilla.org/show_bug.cgi?id=1603536) it might be useful to allow adding descriptions to tables that will then be set as [the table's description on BigQuery](https://cloud.google.com/bigquery/docs/managing-tables#updating_a_tables_description).

I'm not sure what the best approach here is. One way might be doing something similar to how tests for UDFs are defined currently. So having, for example, a `-- Description: ... table description ...` comment inside the template file and updating the description for the table on BigQuery.

I'm open for any other suggestions.

**Comment by jklukas** [comment]
There was a proposal a while ago for adding `metadata.yaml` files in the directories alongside `query.sql` files. The metadata file would be a great place for table descriptions, clustering definitions, etc. We could also put info about dependencies and scheduling in there if we moved forward with the idea of automating creation of a DAG from bigquery-etl queries.

**Comment by scholtzan** [comment]
Sounds related to https://github.com/mozilla/bigquery-etl/issues/296

**Comment by scholtzan** [comment]
I guess that is the proposal: https://docs.google.com/document/d/1zJtRTiiBxpE6faf-HNL6IVTXIFHXvceKCxWXYM0wf9w

**Comment by jklukas** [comment]
> I guess that is the proposal: https://docs.google.com/document/d/1zJtRTiiBxpE6faf-HNL6IVTXIFHXvceKCxWXYM0wf9w

Indeed!
