### ISSUE TITLE
Remove templates/

### ISSUE THREAD

**Issue by relud** [mozilla/bigquery-etl#706]
keeping `templates/` separate from `sql/` was initially a mitigation until persistent UDFs became available. We have a variety of options now for going back to just having `sql/`, including:
- use persistent UDFs
  - would need to replace persistent UDFs with temporary UDFs when running tests, so that UDF changes are properly tested
- modify `script/generate_sql` to work on files in-place
  - could obscure the difference between UDFs defined in `udf*/*.sql` and UDFs currently defined in `templates/*/query.sql`
- create a new script that prepends UDF definitions at run-time
  - could benefit from a bot to automatically comment on PRs with a list of queries impacted by modified UDFs, or something like that

**Comment by jklukas** [comment]
I think we may want to build more support in bigquery-etl for generating queries/views such that maybe continuing to have a `templates` directory is a good thing for the long term. I'm imagining that `generate_sql` could evolve to run a series of modules. These could include:

- Inject temporary UDF definitions (as already exists)
- Run custom scripts for query generation (such as the existing `templates/telemetry/longitudinal.sql.py` and other python scripts that we rely on folks running manually)
- Generate daily and last_seen aggregate queries for all Glean products
- Generate Airflow DAGs based on `metadata.yaml` files

I'm seeing a lot of potential flexibility and value from code generation and I really like being able to see the generated results in PRs alongside changes to the templates.

**Comment by relud** [comment]
discussed with Ben-Wu, jklukas, sunahsuh, and scholtzan in person and determined we should:

> - use persistent UDFs
