### ISSUE TITLE
Document command to run all CI checks locally

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/bigquery-etl#750]
Currently, checks for python formatting and linting are documented only in the CI configuration file. It would be useful to run linting checks locally to avoid running into CircleCI failures on pushes to a branch.

Something along the lines of `circleci local execute` would be useful to have in the README.

**Comment by scholtzan** [comment]
I added documentation in https://github.com/mozilla/bigquery-etl/pull/914 since I had to figure this out for setting up integration tests.

**Comment by dexter030199** [comment]
ff
