### ISSUE TITLE
Discrepancy between Amplitude and BQ tables on user count for each entrypoint 

### ISSUE THREAD

**Issue by Danica076** [mozilla/bigquery-etl#753]
This initiated when I looked into FxA user signup for each entrypoint, especially firstrun and found that there's a big discrepancy between amplitude's number and bigquery's so I reached out to Leif.
RE Leif: the amplitude numbers most likely only include users who started the registration flow with entrypoint = firstrun and did not switch to another entrypoint to finish. So in that sense, they are the more conservative numbers. The BQ tables may include users that started the registration process on firstrun but then e.g. finished the process by confirming their email on the desktop.
In the BQ tables there is a  first_service_flow variable that we could use to investigate this.

**Comment by jklukas** [comment]
This pipeline to Amplitude is no longer relevant.
