### ISSUE TITLE
Normalize main payload causing some queries on telemetry.main to be too complex

### ISSUE THREAD

**Issue by BenWu** [mozilla/bigquery-etl#762]
It looks like this change to the main ping view https://github.com/mozilla/bigquery-etl/blob/88e184525c33eba5e55b5632e5a485b35fdd0277/script/generate_views#L170-L174
is causing some queries to be too complex: https://mozilla.slack.com/archives/C4D5ZA91B/p1582582597019000

`normalize_main_payload` only affects `payload.info.session_length` so it's possible to change the field directly without the udf but this isn't a scalable solution if we need to normalize more fields.  I haven't though too much about long-term solutions to prevent this from happening in the future.  I'm not sure if this problem is affecting any other users so this might not be high priority.  Possible workaround is to access the ping table directly but that isn't preferred as views are the user-facing thing.

**Comment by jklukas** [comment]
Here's confirmation that indeed the addition of this UDF makes the query too complex. I can replace the reference to the view with the expansion of the view:

```
    FROM (
      SELECT
        * 
        REPLACE( `moz-fx-data-shared-prod.udf.normalize_metadata`(metadata) AS metadata 
        , `moz-fx-data-shared-prod.udf.normalize_main_payload`(payload) AS payload
        )
      FROM
        `moz-fx-data-shared-prod.telemetry_stable.main_v4`)
```

The query is still too complex. If I remove the call to `normalize_main_payload`, it becomes runnable. So this query happens to hit the limit. I think it's worth asking Google whether this is a hard limit of the service, or if it's possible to increase the available resources. It would also be worth checking whether expanding the UDF to its literal definition in the view would make the query any less complex.

**Comment by jklukas** [comment]
It looks like replacing the UDF with its definition still leads to the query being too complex. These nested SELECT AS STRUCT calls and destructurings appear to be fairly expensive in terms of the query complexity budget.

**Comment by jklukas** [comment]
I've filed support case 22265171 with Google about this problem.

**Comment by jklukas** [comment]
Quick update here that we're having an ongoing conversation with Google in the support case.

**Comment by jklukas** [comment]
Google opened a public feature request for a `REPLACE_FIELDS` function that would address our needs https://issuetracker.google.com/issues/151892610 but it is not on the roadmap at this time.
