### ISSUE TITLE
Consider more fine-grained UDF approach

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#783]
Currently we have different datasets/tables that use different UDFs, and some of them are very specific. It might make sense to have both project-specific UDFs (as perhaps `udf_*` datasets) and then the general `udf` dataset that contains the ones we want the public to use.

Examples of UDFs that the public not need know about are `add_monthly_searches` and `add_monthly_engine_searches`.

This approach may also make looking over UDFs for a specific ETL easier, e.g. GLAM or clients_last_seen.

**Comment by acmiyaguchi** [comment]
We have mozfun for this now, which is fine-grained enough for general purpose use.
