### ISSUE TITLE
Event queries fail with RecursionError

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#806]
From [logs in Airflow](https://workflow.telemetry.mozilla.org/log?task_id=bq_main_events&dag_id=main_summary&execution_date=2020-03-10T01%3A00%3A00%2B00%3A00) it looks like main_events and event_events queries failed last night, even though the tasks show success in Airflow.

The error is:

> RecursionError: maximum recursion depth exceeded

And it looks like it's coming from the `bq` CLI. This may have something to do with the new wrapper we have for queries in the `entrypoint` script. We need to figure out how to get these queries running, and also how to make sure the script passes through the correct exit code.

cc @relud @scholtzan

**Comment by jklukas** [comment]
We may want to look into using [os.execv](https://docs.python.org/3/library/os.html#os.execv) or similar to actually replace the python process with the script it's invoking.

**Comment by scholtzan** [comment]
[subprocess.check_call](https://docs.python.org/2/library/subprocess.html#subprocess.check_call) might also be an option here.

**Comment by jklukas** [comment]
It looks like the os.execv option would be pretty ugly due to the need to pipe in the query contents: https://stackoverflow.com/a/24514542/1260237

**Comment by jklukas** [comment]
I was able to successfully rerun the task!
