### ISSUE TITLE
GLAM queries fail with "Argument list too long"

### ISSUE THREAD

**Issue by scholtzan** [mozilla/bigquery-etl#807]
Some GLAM queries such as `clients_daily_histogram_aggregates` fail with `OSError: [Errno 7] Argument list too long: 'bq'`. This is related to the new wrapper for running queries.

See: https://workflow.telemetry.mozilla.org/log?execution_date=2020-03-10T00%3A00%3A00%2B00%3A00&dag_id=glam&task_id=clients_daily_histogram_aggregates

Also potentially related to https://github.com/mozilla/bigquery-etl/issues/806

cc @emtwo

**Comment by jklukas** [comment]
I think the problem here is that we used to do `bq <args> < path_to_query` but we now do `bq <args> query_text`. For long query text, we exceed the size that bash is able to handle.

We need to pipe the contents of the file into the invocation.

**Comment by scholtzan** [comment]
Indeed. https://github.com/mozilla/bigquery-etl/pull/808 fixes this issue
