### ISSUE TITLE
Variable assignment inside conditional under histogram_percentiles_v1

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/bigquery-etl#831]
https://github.com/mozilla/bigquery-etl/blob/029b06e342d36312c928054824634b5317b41dd6/sql/telemetry_derived/histogram_percentiles_v1/query.sql#L36

I was reading through the source for `udf_percentile`. The line above looks like a typo, which may be producing incorrect values for linear histogram percentiles.

@emtwo

**Comment by emtwo** [comment]
Oh good catch! For reference, this was the original function that was reused: https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/v2/telemetry.js#L90
