### ISSUE TITLE
Script for running glean usage ETL (baseline_daily and baseline_last_seen)

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#848]
We are pretty close to having a generic methodology for usage ETL (clients_daily and clients_last_seen) on top of Glean baseline pings. Currently, we need to copy/paste and manually modify queries for each new glean application, then also manually add those to Airflow.

I propose that instead, we write a script similar to `copy_deduplicate` that uses the BQ API to dynamically fetch info about tables and runs queries for all Glean applications in one job. In this case, the script would discover all datasets that represent glean apps, and run `baseline_daily` and `baseline_last_seen` queries for all of them.

We would remove existing queries and Airflow jobs for Fenix and VR browser, and instead let this new script create the tables and populate them.

We would add two new Airflow jobs that make invocations like the following:

- `scripts/run_glean_baseline_daily --date 2020-03-20`
- `scripts/run_glean_baseline_last_seen --date 2020-03-20` (would have depends_on_past=True)

Pros:

- We would be picking up glean apps dynamically, so each new glean app would automatically get `baseline_daily` and `baseline_last_seen` without any manual intervention

Cons:

- This is less direct than the current approach, so adds some cognitive load for consumers of this repo to understand how the tables get populated
- We currently have custom logic for Fenix and VR browser to pull in info from `metrics` pings and join it to the baseline ping data. The new approach is cutting some scope here, as the existing `metrics` data is not necessary for meeting needs of GUD or the Fennec-to-Fenix migration dashboard. We could assess an approach for adding in metrics data as a future improvement. For the time being, I think simplicity should be preferred for meeting the real needs we know of.

I would plan to take on this work, as my major motivation is about getting a firm methodology in place to be able to feed this data into GUD.

**Comment by jklukas** [comment]
cc @relud @scholtzan

**Comment by acmiyaguchi** [comment]
It's worth considering using Jinja to template queries. They can be formatted with `format_sql` (with [minor modifications](https://github.com/mozilla/bigquery-etl/pull/730)), and it forces separation between query logic and the script. 

Also, what's your approach for enumerating the Glean products with datasets? Are you going to be filtering the tables based on the repositories in the probe info service?

**Comment by jklukas** [comment]
> It's worth considering using Jinja to template queries. They can be formatted with `format_sql` (with [minor modifications](https://github.com/mozilla/bigquery-etl/pull/730)), and it forces separation between query logic and the script.

Yes, I was planning to do that and put the main logic under `bigquery_etl` to try to keep it consistent with what already exists for glam.

> Also, what's your approach for enumerating the Glean products with datasets? Are you going to be filtering the tables based on the repositories in the probe info service?

I'd plan to use a similar approach to what we do in view publishing. I'd look for stable tables named `baseline_v1` and which have a `schema_id` tag consistent with glean. Then we'd construct destination table names based on those.

**Comment by acmiyaguchi** [comment]
> I'd plan to use a similar approach to what we do in view publishing. I'd look for stable tables named `baseline_v1` and which have a `schema_id` tag consistent with glean. Then we'd construct destination table names based on those.

Oh interesting, I didn't know we had metadata for published glean tables. That's simpler than what I thought it would be.
