### ISSUE TITLE
Canonical mapping of mobile product names

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#861]
See https://github.com/mozilla/firefox-data-docs/pull/431#discussion_r400368399

> I have heard many people voice a need for a map between different ways of labeling products. It gets very confusing across stakeholders.

We could create a `static` table that gives a canonical mapping of low-level `app_name`/`channel`/`app_id` to high-level application name, but it's a nuanced problem. The needed field differs between core pings and Glean-based apps, etc.

**Comment by acmiyaguchi** [comment]
I believe `mozfun.norm.fenix_app_info` has resolved most of the issues here (https://github.com/mozilla/bigquery-etl/blob/master/sql/mozfun/norm/fenix_app_info/metadata.yaml), which is used most recently in this PR https://github.com/mozilla/bigquery-etl/pull/1380
