### ISSUE TITLE
clients_daily_scalar_aggregates_v1 contains a lot of redundant values

### ISSUE THREAD

**Issue by BenWu** [mozilla/bigquery-etl#919]
clients_daily_scalar_aggregates contains metric name and types for every key, process, agg_type combination in each row:

![Screen Shot 2020-04-21 at 11 12 01 AM](https://user-images.githubusercontent.com/12437227/79890249-38a39380-83cd-11ea-8a4a-252c00b35c06.png)

This can be improved by using a nested struct for each metric so that the name, type, and key are only stored once per row:

![Screen Shot 2020-04-21 at 11 20 17 AM](https://user-images.githubusercontent.com/12437227/79890384-68529b80-83cd-11ea-8313-99b8fb54aa56.png)

This would break the existing schema but that should be easy to deal with by modifying the existing table in place and updating the downstream query.

A further improvement is to not store metrics with only null values but I'm not sure if there's some downstream need for retaining those values.

From testing on a 1% sample, the above schema change would reduce the table size to ~29%, not storing nulls would reduce to ~31%, and doing both would reduce to  ~12.3%.  This reduce storage costs significantly.  If we change to a 7 day retention period for clients_daily_scalar, this would save around $150-$180 a week on storage and some more on downstream etl data scanned (maybe another couple hundred).  This isn't huge but worth considering.

**Comment by edugfilho** [comment]
This issue is now being tracked in https://github.com/mozilla/glam/issues/2654
