### ISSUE TITLE
Coordinate method for query templating

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#953]
Query templating is an important feature that this repository needs to support as a first-class citizen.

We currently have a few methods (at least two) for query templating - jinja, and python formatting. This issue is for deciding which of those is the better method, and adding some utilities to make templating easy for new queries.

cc @acmiyaguchi

**Comment by jklukas** [comment]
Jinja is definitely more flexible and can handle some complex use cases elegantly. I'm fine with having some mix of python formatting, but generally only for cases simple enough that you can write the query template within the python source file directly. Wehn we split out query templates to their own file, I think we should standardize on jinja.

**Comment by acmiyaguchi** [comment]
I agree with Jeff. I think they both have their use cases. I've used Python formatting for queries, but only in cases where they've been inlined in the script. In the case that's linked here, I would prefer Jinja. It's about as straightforward and battle tested as you can get for a templating language with flow control mechanisms. The API is simple and the documentation is great. 

The one high value utility I see is having the sql formatter support Jinja. I've had a draft open https://github.com/mozilla/bigquery-etl/pull/730 for months, but there are some edge cases that need to be handled. This would effectively incentivize all templated files to be compatible with Jinja syntax so they can benefit from formatting.

**Comment by ANich** [comment]
I think at this point we have a pretty solid "framework" for this in bigquery-etl `sql_generator`'s. What do you think now @scholtzan @fbertsch
