### ISSUE TITLE
Add error bars to histograms in Glam

### ISSUE THREAD

**Issue by emtwo** [mozilla/bigquery-etl#954]
The computation for error bars are as described here in case 1:
https://docs.google.com/document/d/1ipy1oFIKDvHr3R6Ku0goRjS11R1ZH1z2gygOGkSdqUg/edit#heading=h.8gnzmf4a2hjh

**Comment by edugfilho** [comment]
We're tracking this issue in the GLAM repo here https://github.com/mozilla/glam/issues/2654
