### ISSUE TITLE
Add a task in the desktop glam dag to create a table mapping probe -> processes

### ISSUE THREAD

**Issue by emtwo** [mozilla/bigquery-etl#955]

**Comment by emtwo** [comment]
The glam frontend needs to know which processes a probe can contain before it fetches all the data for that probe. This way, it can decide which processes to show in the dropdown for that probe.

So we need a separate, smaller table that can be pulled in by the frontend first that has a mapping for each probe to the list of processes it contains.

We can find this by reading from `moz-fx-data-shared-prod.telemetry_derived.client_probe_counts_v1` to find what processes we have data for, for each probe.

**Comment by Ben-Wu** [comment]
Should we also group these processes by os and channel like the frontend?  Channel seems to matter https://sql.telemetry.mozilla.org/queries/71370/source
I expect that we don't need to group by key though, is that correct?

**Comment by emtwo** [comment]
> Should we also group these processes by os and channel like the frontend? Channel seems to matter https://sql.telemetry.mozilla.org/queries/71370/source
> I expect that we don't need to group by key though, is that correct?

Yes! That all sounds correct. Good idea to group by os and channel and not by key.
