### ISSUE TITLE
Deploy UDFs to a public mozudf project

### ISSUE THREAD

**Issue by jklukas** [mozilla/bigquery-etl#969]
We have various folks such as Data Science who are encouraged to run queries in team-specific projects. They end up needing to fully qualify UDF references since the UDFs are not published in the DS project.

We could provision a new publicly-accessible project called something simple like `mozudf` and then UDF references could look like `mozudf.sql.json_extract_histogram` or `mozudf.js.gunzip`, no backticks needed, and it would no longer matter what project you're in. Or we could provision datasets by usage, so maybe we'd have `mozudf.bits28.range`, etc.

**Comment by fbertsch** [comment]
Yes, please! Some discussion here as well: https://github.com/mozilla/bigquery-etl/issues/783. Having dataset-specific UDFs would really ease the cognitive burden.

**Comment by tdsmith** [comment]
Yes, please! This would save a lot of typing in non-redash contexts.

When building integration tests for pensieve @scholtzan and I also ran into a case where we wanted these UDFs available in the context of a service worker account without any privileges to our usual projects.

**Comment by jklukas** [comment]
Starting a discussion about provisioning such a project in https://bugzilla.mozilla.org/show_bug.cgi?id=1637749

**Comment by scholtzan** [comment]
I think provisioning datasets by usage might be more intuitive since for external users implementation details (whether the UDF is written in SQL or JavaScript) might be less relevant. Also long-term or as part of this effort it might also be nice to publish descriptions for public UDFs which might be useful for new or external users.

**Comment by jklukas** [comment]
> Also long-term or as part of this effort it might also be nice to publish descriptions for public UDFs which might be useful for new or external users.

Yes! I agree it's now time to do this, and it should be rolled into this project. I also feel like @wlach's work around defining DTMO's purpose is giving more clarity here. Previously, we had flagged that we should be pushing UDF docs to DTMO (https://github.com/mozilla/bigquery-etl/issues/228) but I now feel like we have permission to publish docs alongside this repo, which will be easier to maintain.

**Comment by scholtzan** [comment]
It feels like having a `metadata.yaml` alongside each UDF which contains the description and a flag of whether the UDF should be public would be the right way to go. This would also match with what we already have for queries.
I think it might be worth having a short proposal describing these changes. I'd be happy to put one together if you think that makes sense?

**Comment by jklukas** [comment]
> It feels like having a metadata.yaml alongside each UDF which contains the description and a flag of whether the UDF should be public would be the right way to go

The naming may be different between what we currently have under `udf/` and what we'll want to call a function in `mozudf`. We may actually want to create a new directory structure for `mozudf` and define the new clean names and metadata there. Then we could redefine some of the `udf`s as simple wrappers that call the `mozudf` versions.

I also want to make it easy to write rich documentation. It's tempting to put docs in the `metadata.yaml`, but that may get onerous for including code blocks with examples, etc.

**Comment by wlach** [comment]
> I also want to make it easy to write rich documentation. It's tempting to put docs in the `metadata.yaml`, but that may get onerous for including code blocks with examples, etc.

I've been thinking a bit about this problem in general for a (hypothetical) dataset documentation viewer: I wonder if we could specify example queries in something like metadata.yaml, then their content into inserted into a templatized markdown file. So given this kind of `metadata.yaml`:

```yaml
name: udf.histogram_percentiles
description: Given histogram and list of percentiles, calculate what those percentiles are for the histogram. If the histogram is empty, returns NULL.
examples:
    - title: Simple example
      description: Calculate percentiles for FX_TAB_SWITCH_SPINNER_VISIBLE_LONG_MS probe on Windows Nightly
      sql: >
        select percentile, COUNT(*)
        FROM telemetry.main
        CROSS JOIN UNNEST (histogram_percentiles(udf.json_extract_histogram(payload.histograms.FX_TAB_SWITCH_SPINNER_VISIBLE_LONG_MS), [.5])) AS percentile
        WHERE
            application.channel='nightly'
            AND normalized_os='Windows'
            AND application.build_id > FORMAT_DATE("%Y%m%d", DATE_SUB(CURRENT_DATE(), INTERVAL 2 QUARTER))
            AND DATE(submission_timestamp) = '2020-04-20'
            AND sample_id=42
        GROUP BY
            percentile
```

We could parse that into:

```md
# udf.histogram_percentiles

Given histogram and list of percentiles, calculate what those percentiles are for the histogram.
If the histogram is empty, returns NULL.

## Example Queries

### Simple example

Calculate percentiles for FX_TAB_SWITCH_SPINNER_VISIBLE_LONG_MS probe on Windows Nightly

```sql
        select percentile, COUNT(*)
        FROM telemetry.main
        CROSS JOIN UNNEST (histogram_percentiles(udf.json_extract_histogram(payload.histograms.FX_TAB_SWITCH_SPINNER_VISIBLE_LONG_MS), [.5])) AS percentile
        WHERE
            application.channel='nightly'
            AND normalized_os='Windows'
            AND application.build_id > FORMAT_DATE("%Y%m%d", DATE_SUB(CURRENT_DATE(), INTERVAL 2 QUARTER))
            AND DATE(submission_timestamp) = '2020-04-20'
            AND sample_id=42
        GROUP BY
            percentile
```
```

Nice things about this:
* easy to generate links to sections in the markdown
* documentation could potentially include tests

We could bikeshed on details but I think this is pretty reasonable for a first draft.

**Comment by jklukas** [comment]
> could potentially test examples to make sure they actually work

I very much like this feature.

I appreciate your full yaml example and how the markdown would look. I still worry that that's going to feel awkward to edit compared to writing documentation in a straight markdown file.

I also think it's going to be important to have dataset-level documentation for sets of related UDFs, so I don't want to end up with a model that's too tied to the idea of documentation being tied directly to individual functions.

**Comment by scholtzan** [comment]
The `mozfun` project is all set up
